// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.Maui;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements
{
    /// <summary>
    /// A view that presents a scrollable collection of items where each item 'snaps' into place after scrolling.
    /// </summary>
    public partial class CarouselView<T> : ItemsView<T>
    {
        static CarouselView()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the currently displayed item in the carousel.
        /// </summary>
        /// <value>
        /// The data item currently centered in the carousel, or <see langword="null" /> if no item is selected.
        /// </value>
        [Parameter] public T CurrentItem { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether bounce effects are enabled when scrolling reaches the end of the carousel.
        /// </summary>
        /// <value>
        /// <see langword="true" /> to enable bounce effects; otherwise, <see langword="false" />. The default is <see langword="true" />.
        /// </value>
        [Parameter] public bool? IsBounceEnabled { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether scrolling between items is animated.
        /// </summary>
        /// <value>
        /// <see langword="true" /> to animate scrolling; otherwise, <see langword="false" />. The default is <see langword="true" />.
        /// </value>
        [Parameter] public bool? IsScrollAnimated { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether swipe gestures are enabled for navigation.
        /// </summary>
        /// <value>
        /// <see langword="true" /> to enable swipe gestures; otherwise, <see langword="false" />. The default is <see langword="true" />.
        /// </value>
        [Parameter] public bool? IsSwipeEnabled { get; set; }
        /// <summary>
        /// Gets or sets the layout used to arrange items in the carousel.
        /// </summary>
        /// <value>
        /// A <see cref="T:Microsoft.Maui.Controls.LinearItemsLayout" /> that defines the layout direction and snap behavior. The default is a horizontal layout with mandatory single snap points.
        /// </value>
        [Parameter] public MC.LinearItemsLayout ItemsLayout { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether the carousel loops back to the first item after reaching the last item.
        /// </summary>
        /// <value>
        /// <see langword="true" /> if the carousel should loop continuously; otherwise, <see langword="false" />. The default is <see langword="true" />.
        /// </value>
        [Parameter] public bool? Loop { get; set; }
        /// <summary>
        /// Gets or sets the amount of space to reserve on each side of the current item to show a peek of adjacent items.
        /// </summary>
        /// <value>
        /// A <see cref="T:Microsoft.Maui.Thickness" /> value defining the peek area insets. The default is 0 on all sides.
        /// </value>
        [Parameter] public Thickness? PeekAreaInsets { get; set; }
        /// <summary>
        /// Gets or sets the index of the currently displayed item in the carousel.
        /// </summary>
        /// <value>
        /// The zero-based index of the current item. The default is 0.
        /// </value>
        [Parameter] public int? Position { get; set; }
        /// <summary>
        /// Occurs when the <see cref="P:Microsoft.Maui.Controls.CarouselView.CurrentItem" /> changes.
        /// </summary>
        [Parameter] public EventCallback<T> CurrentItemChanged { get; set; }
        /// <summary>
        /// Occurs when the <see cref="P:Microsoft.Maui.Controls.CarouselView.Position" /> changes.
        /// </summary>
        [Parameter] public EventCallback<int> PositionChanged { get; set; }

        public new MC.CarouselView NativeControl => (MC.CarouselView)((BindableObject)this).NativeControl;

        protected override MC.CarouselView CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(CurrentItem):
                    if (!Equals(CurrentItem, value))
                    {
                        CurrentItem = CastParameter<T>(value, name);
                        NativeControl.CurrentItem = CurrentItem;
                    }
                    break;
                case nameof(IsBounceEnabled):
                    if (!Equals(IsBounceEnabled, value))
                    {
                        IsBounceEnabled = CastParameter<bool?>(value, name);
                        NativeControl.IsBounceEnabled = IsBounceEnabled ?? (bool)MC.CarouselView.IsBounceEnabledProperty.DefaultValue;
                    }
                    break;
                case nameof(IsScrollAnimated):
                    if (!Equals(IsScrollAnimated, value))
                    {
                        IsScrollAnimated = CastParameter<bool?>(value, name);
                        NativeControl.IsScrollAnimated = IsScrollAnimated ?? (bool)MC.CarouselView.IsScrollAnimatedProperty.DefaultValue;
                    }
                    break;
                case nameof(IsSwipeEnabled):
                    if (!Equals(IsSwipeEnabled, value))
                    {
                        IsSwipeEnabled = CastParameter<bool?>(value, name);
                        NativeControl.IsSwipeEnabled = IsSwipeEnabled ?? (bool)MC.CarouselView.IsSwipeEnabledProperty.DefaultValue;
                    }
                    break;
                case nameof(ItemsLayout):
                    if (!Equals(ItemsLayout, value))
                    {
                        ItemsLayout = CastParameter<MC.LinearItemsLayout>(value, name);
                        NativeControl.ItemsLayout = ItemsLayout;
                    }
                    break;
                case nameof(Loop):
                    if (!Equals(Loop, value))
                    {
                        Loop = CastParameter<bool?>(value, name);
                        NativeControl.Loop = Loop ?? (bool)MC.CarouselView.LoopProperty.DefaultValue;
                    }
                    break;
                case nameof(PeekAreaInsets):
                    if (!Equals(PeekAreaInsets, value))
                    {
                        PeekAreaInsets = CastParameter<Thickness?>(value, name);
                        NativeControl.PeekAreaInsets = PeekAreaInsets ?? (Thickness)MC.CarouselView.PeekAreaInsetsProperty.DefaultValue;
                    }
                    break;
                case nameof(Position):
                    if (!Equals(Position, value))
                    {
                        Position = CastParameter<int?>(value, name);
                        NativeControl.Position = Position ?? (int)MC.CarouselView.PositionProperty.DefaultValue;
                    }
                    break;
                case nameof(CurrentItemChanged):
                    if (!Equals(CurrentItemChanged, value))
                    {
                        void NativeControlCurrentItemChanged(object sender, MC.CurrentItemChangedEventArgs e)
                        {
                            var value = NativeControl.CurrentItem is T item ? item : default(T);
                            CurrentItem = value;
                            InvokeEventCallback(CurrentItemChanged, value);
                        }

                        CurrentItemChanged = CastParameter<EventCallback<T>>(value, name);
                        NativeControl.CurrentItemChanged -= NativeControlCurrentItemChanged;
                        NativeControl.CurrentItemChanged += NativeControlCurrentItemChanged;
                    }
                    break;
                case nameof(PositionChanged):
                    if (!Equals(PositionChanged, value))
                    {
                        void NativeControlPositionChanged(object sender, MC.PositionChangedEventArgs e)
                        {
                            var value = NativeControl.Position;
                            Position = value;
                            InvokeEventCallback(PositionChanged, value);
                        }

                        PositionChanged = CastParameter<EventCallback<int>>(value, name);
                        NativeControl.PositionChanged -= NativeControlPositionChanged;
                        NativeControl.PositionChanged += NativeControlPositionChanged;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
