// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements
{
    /// <summary>
    /// A <see cref="T:Microsoft.Maui.Controls.View" /> that presents local HTML content in a web view and allows JavaScript and C# code to communicate by using messages and by invoking methods.
    /// </summary>
    public partial class HybridWebView : View
    {
        static HybridWebView()
        {
            RegisterAdditionalHandlers();
        }

        [Parameter] public string DefaultFile { get; set; }
        [Parameter] public string HybridRoot { get; set; }
        /// <summary>
        /// Raised when a raw message is received from the web view. Raw messages are strings that have no additional processing.
        /// </summary>
        [Parameter] public EventCallback<MC.HybridWebViewRawMessageReceivedEventArgs> OnRawMessageReceived { get; set; }
        /// <summary>
        /// Raised when the web view is initializing. This event allows the application to perform additional configuration.
        /// </summary>
        [Parameter] public EventCallback<MC.WebViewInitializingEventArgs> OnWebViewInitializing { get; set; }
        /// <summary>
        /// Raised when the web view has been initialized.
        /// </summary>
        [Parameter] public EventCallback<MC.WebViewInitializedEventArgs> OnWebViewInitialized { get; set; }
        /// <summary>
        /// Raised when a web resource is requested. This event allows the application to intercept the request and provide a custom response. The event handler can set the <see cref="P:Microsoft.Maui.Controls.WebViewWebResourceRequestedEventArgs.Handled" /> property to true to indicate that the request has been handled and no further processing is needed. If the event handler does set this property to true, it must also call the <see cref="M:Microsoft.Maui.Controls.WebViewWebResourceRequestedEventArgs.SetResponse(System.Int32,System.String,System.Collections.Generic.IReadOnlyDictionary{System.String,System.String},System.IO.Stream)" /> or <see cref="M:Microsoft.Maui.Controls.WebViewWebResourceRequestedEventArgs.SetResponse(System.Int32,System.String,System.Collections.Generic.IReadOnlyDictionary{System.String,System.String},System.Threading.Tasks.Task{System.IO.Stream})" /> method to provide a response to the request.
        /// </summary>
        [Parameter] public EventCallback<MC.WebViewWebResourceRequestedEventArgs> OnWebResourceRequested { get; set; }

        public new MC.HybridWebView NativeControl => (MC.HybridWebView)((BindableObject)this).NativeControl;

        protected override MC.HybridWebView CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(DefaultFile):
                    if (!Equals(DefaultFile, value))
                    {
                        DefaultFile = (string)value;
                        NativeControl.DefaultFile = DefaultFile;
                    }
                    break;
                case nameof(HybridRoot):
                    if (!Equals(HybridRoot, value))
                    {
                        HybridRoot = (string)value;
                        NativeControl.HybridRoot = HybridRoot;
                    }
                    break;
                case nameof(OnRawMessageReceived):
                    if (!Equals(OnRawMessageReceived, value))
                    {
                        void NativeControlRawMessageReceived(object sender, MC.HybridWebViewRawMessageReceivedEventArgs e) => InvokeEventCallback(OnRawMessageReceived, e);

                        OnRawMessageReceived = (EventCallback<MC.HybridWebViewRawMessageReceivedEventArgs>)value;
                        NativeControl.RawMessageReceived -= NativeControlRawMessageReceived;
                        NativeControl.RawMessageReceived += NativeControlRawMessageReceived;
                    }
                    break;
                case nameof(OnWebViewInitializing):
                    if (!Equals(OnWebViewInitializing, value))
                    {
                        void NativeControlWebViewInitializing(object sender, MC.WebViewInitializingEventArgs e) => InvokeEventCallback(OnWebViewInitializing, e);

                        OnWebViewInitializing = (EventCallback<MC.WebViewInitializingEventArgs>)value;
                        NativeControl.WebViewInitializing -= NativeControlWebViewInitializing;
                        NativeControl.WebViewInitializing += NativeControlWebViewInitializing;
                    }
                    break;
                case nameof(OnWebViewInitialized):
                    if (!Equals(OnWebViewInitialized, value))
                    {
                        void NativeControlWebViewInitialized(object sender, MC.WebViewInitializedEventArgs e) => InvokeEventCallback(OnWebViewInitialized, e);

                        OnWebViewInitialized = (EventCallback<MC.WebViewInitializedEventArgs>)value;
                        NativeControl.WebViewInitialized -= NativeControlWebViewInitialized;
                        NativeControl.WebViewInitialized += NativeControlWebViewInitialized;
                    }
                    break;
                case nameof(OnWebResourceRequested):
                    if (!Equals(OnWebResourceRequested, value))
                    {
                        void NativeControlWebResourceRequested(object sender, MC.WebViewWebResourceRequestedEventArgs e) => InvokeEventCallback(OnWebResourceRequested, e);

                        OnWebResourceRequested = (EventCallback<MC.WebViewWebResourceRequestedEventArgs>)value;
                        NativeControl.WebResourceRequested -= NativeControlWebResourceRequested;
                        NativeControl.WebResourceRequested += NativeControlWebResourceRequested;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
