// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.Maui;
using Microsoft.Maui.Graphics;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements
{
    /// <summary>
    /// Represents a portion of formatted text for use in a FormattedString.
    /// </summary>
    public partial class Span : GestureElement
    {
        static Span()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the background color for the span.
        /// </summary>
        [Parameter] public Color BackgroundColor { get; set; }
        /// <summary>
        /// Gets or sets the character spacing for the span.
        /// </summary>
        [Parameter] public double? CharacterSpacing { get; set; }
        /// <summary>
        /// Gets or sets the font attributes for the span.
        /// </summary>
        [Parameter] public MC.FontAttributes? FontAttributes { get; set; }
        [Parameter] public bool? FontAutoScalingEnabled { get; set; }
        /// <summary>
        /// Gets or sets the font family for the span.
        /// </summary>
        [Parameter] public string FontFamily { get; set; }
        /// <summary>
        /// Gets or sets the font size for the span.
        /// </summary>
        [Parameter] public double? FontSize { get; set; }
        /// <summary>
        /// Gets or sets the line height multiplier for the span.
        /// </summary>
        [Parameter] public double? LineHeight { get; set; }
        /// <summary>
        /// Gets or sets the style for the span.
        /// </summary>
        [Parameter] public MC.Style Style { get; set; }
        /// <summary>
        /// Gets or sets the text content of the span.
        /// </summary>
        [Parameter] public string Text { get; set; }
        /// <summary>
        /// Gets or sets the text color for the span.
        /// </summary>
        [Parameter] public Color TextColor { get; set; }
        /// <summary>
        /// Gets or sets the text decorations for the span.
        /// </summary>
        [Parameter] public TextDecorations? TextDecorations { get; set; }
        /// <summary>
        /// Gets or sets the text transform for the span.
        /// </summary>
        [Parameter] public TextTransform? TextTransform { get; set; }

        public new MC.Span NativeControl => (MC.Span)((BindableObject)this).NativeControl;

        protected override MC.Span CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(BackgroundColor):
                    if (!Equals(BackgroundColor, value))
                    {
                        BackgroundColor = CastParameter<Color>(value, name);
                        NativeControl.BackgroundColor = BackgroundColor;
                    }
                    break;
                case nameof(CharacterSpacing):
                    if (!Equals(CharacterSpacing, value))
                    {
                        CharacterSpacing = CastParameter<double?>(value, name);
                        NativeControl.CharacterSpacing = CharacterSpacing ?? (double)MC.Span.CharacterSpacingProperty.DefaultValue;
                    }
                    break;
                case nameof(FontAttributes):
                    if (!Equals(FontAttributes, value))
                    {
                        FontAttributes = CastParameter<MC.FontAttributes?>(value, name);
                        NativeControl.FontAttributes = FontAttributes ?? (MC.FontAttributes)MC.Span.FontAttributesProperty.DefaultValue;
                    }
                    break;
                case nameof(FontAutoScalingEnabled):
                    if (!Equals(FontAutoScalingEnabled, value))
                    {
                        FontAutoScalingEnabled = CastParameter<bool?>(value, name);
                        NativeControl.FontAutoScalingEnabled = FontAutoScalingEnabled ?? (bool)MC.Span.FontAutoScalingEnabledProperty.DefaultValue;
                    }
                    break;
                case nameof(FontFamily):
                    if (!Equals(FontFamily, value))
                    {
                        FontFamily = CastParameter<string>(value, name);
                        NativeControl.FontFamily = FontFamily;
                    }
                    break;
                case nameof(FontSize):
                    if (!Equals(FontSize, value))
                    {
                        FontSize = CastParameter<double?>(value, name);
                        NativeControl.FontSize = FontSize ?? (double)MC.Span.FontSizeProperty.DefaultValue;
                    }
                    break;
                case nameof(LineHeight):
                    if (!Equals(LineHeight, value))
                    {
                        LineHeight = CastParameter<double?>(value, name);
                        NativeControl.LineHeight = LineHeight ?? (double)MC.Span.LineHeightProperty.DefaultValue;
                    }
                    break;
                case nameof(Style):
                    if (!Equals(Style, value))
                    {
                        Style = CastParameter<MC.Style>(value, name);
                        NativeControl.Style = Style;
                    }
                    break;
                case nameof(Text):
                    if (!Equals(Text, value))
                    {
                        Text = CastParameter<string>(value, name);
                        NativeControl.Text = Text;
                    }
                    break;
                case nameof(TextColor):
                    if (!Equals(TextColor, value))
                    {
                        TextColor = CastParameter<Color>(value, name);
                        NativeControl.TextColor = TextColor;
                    }
                    break;
                case nameof(TextDecorations):
                    if (!Equals(TextDecorations, value))
                    {
                        TextDecorations = CastParameter<TextDecorations?>(value, name);
                        NativeControl.TextDecorations = TextDecorations ?? (TextDecorations)MC.Span.TextDecorationsProperty.DefaultValue;
                    }
                    break;
                case nameof(TextTransform):
                    if (!Equals(TextTransform, value))
                    {
                        TextTransform = CastParameter<TextTransform?>(value, name);
                        NativeControl.TextTransform = TextTransform ?? (TextTransform)MC.Span.TextTransformProperty.DefaultValue;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
