// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements
{
    /// <summary>
    /// Represents a control that allows a user to incrementally adjust a numeric value by tapping plus or minus buttons.
    /// </summary>
    public partial class Stepper : View
    {
        static Stepper()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the amount by which the stepper value changes with each button press.
        /// </summary>
        /// <value>
        /// The increment value. The default is 1.
        /// </value>
        [Parameter] public double? Increment { get; set; }
        /// <summary>
        /// Gets or sets the maximum value of the stepper.
        /// </summary>
        /// <value>
        /// The maximum value. The default is 100.
        /// </value>
        [Parameter] public double? Maximum { get; set; }
        /// <summary>
        /// Gets or sets the minimum value of the stepper.
        /// </summary>
        /// <value>
        /// The minimum value. The default is 0.
        /// </value>
        [Parameter] public double? Minimum { get; set; }
        /// <summary>
        /// Gets or sets the current value of the stepper.
        /// </summary>
        /// <value>
        /// The current value, clamped between <see cref="P:Microsoft.Maui.Controls.Stepper.Minimum" /> and <see cref="P:Microsoft.Maui.Controls.Stepper.Maximum" />. The default is 0.
        /// </value>
        [Parameter] public double? Value { get; set; }
        /// <summary>
        /// Occurs when the <see cref="P:Microsoft.Maui.Controls.Stepper.Value" /> property changes.
        /// </summary>
        [Parameter] public EventCallback<double> ValueChanged { get; set; }

        public new MC.Stepper NativeControl => (MC.Stepper)((BindableObject)this).NativeControl;

        protected override MC.Stepper CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Increment):
                    if (!Equals(Increment, value))
                    {
                        Increment = CastParameter<double?>(value, name);
                        NativeControl.Increment = Increment ?? (double)MC.Stepper.IncrementProperty.DefaultValue;
                    }
                    break;
                case nameof(Maximum):
                    if (!Equals(Maximum, value))
                    {
                        Maximum = CastParameter<double?>(value, name);
                        NativeControl.Maximum = Maximum ?? (double)MC.Stepper.MaximumProperty.DefaultValue;
                    }
                    break;
                case nameof(Minimum):
                    if (!Equals(Minimum, value))
                    {
                        Minimum = CastParameter<double?>(value, name);
                        NativeControl.Minimum = Minimum ?? (double)MC.Stepper.MinimumProperty.DefaultValue;
                    }
                    break;
                case nameof(Value):
                    if (!Equals(Value, value))
                    {
                        Value = CastParameter<double?>(value, name);
                        NativeControl.Value = Value ?? (double)MC.Stepper.ValueProperty.DefaultValue;
                    }
                    break;
                case nameof(ValueChanged):
                    if (!Equals(ValueChanged, value))
                    {
                        void NativeControlValueChanged(object sender, MC.ValueChangedEventArgs e)
                        {
                            var value = NativeControl.Value;
                            Value = value;
                            InvokeEventCallback(ValueChanged, value);
                        }

                        ValueChanged = CastParameter<EventCallback<double>>(value, name);
                        NativeControl.ValueChanged -= NativeControlValueChanged;
                        NativeControl.ValueChanged += NativeControlValueChanged;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
