// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using SMTC = Syncfusion.Maui.Toolkit.Charts;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Charts
{
    /// <summary>
    /// Represent the line style for the <see cref="T:Syncfusion.Maui.Toolkit.Charts.ErrorBarSeries" />
    /// </summary>
    public partial class ErrorBarLineStyle : ChartLineStyle
    {
        static ErrorBarLineStyle()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the stroke cap style to customize the stroke cap appearance.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Syncfusion.Maui.Toolkit.Charts.ErrorBarStrokeCap" /> values and its defaults value is <see cref="F:Syncfusion.Maui.Toolkit.Charts.ErrorBarStrokeCap.Flat"></see>
        /// </value>
        [Parameter] public SMTC.ErrorBarStrokeCap? StrokeCap { get; set; }

        public new SMTC.ErrorBarLineStyle NativeControl => (SMTC.ErrorBarLineStyle)((BindableObject)this).NativeControl;

        protected override SMTC.ErrorBarLineStyle CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(StrokeCap):
                    if (!Equals(StrokeCap, value))
                    {
                        StrokeCap = (SMTC.ErrorBarStrokeCap?)value;
                        NativeControl.StrokeCap = StrokeCap ?? (SMTC.ErrorBarStrokeCap)SMTC.ErrorBarLineStyle.StrokeCapProperty.DefaultValue;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
