// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using SMTC = Syncfusion.Maui.Toolkit.Charts;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Charts
{
    /// <summary>
    /// The <see cref="T:Syncfusion.Maui.Toolkit.Charts.HiLoOpenCloseSeries" /> displays a set of OHLC segments used in financial analysis to represent open, high, low, and close values of an asset or security.
    /// </summary>
    public partial class HiLoOpenCloseSeries<T> : FinancialSeriesBase<T>
    {
        static HiLoOpenCloseSeries()
        {
            RegisterAdditionalHandlers();
        }

        public new SMTC.HiLoOpenCloseSeries NativeControl => (SMTC.HiLoOpenCloseSeries)((BindableObject)this).NativeControl;

        protected override SMTC.HiLoOpenCloseSeries CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
