// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using SMTC = Syncfusion.Maui.Toolkit.Charts;
using System;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Charts
{
    /// <summary>
    /// The numerical axis uses a numerical scale and it displays numbers as labels. It supports both horizontal and vertical axes.
    /// </summary>
    public partial class NumericalAxis : RangeAxisBase
    {
        static NumericalAxis()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets a value that determines the interval in axis's range.
        /// </summary>
        /// <value>
        /// The default value is double.NaN.
        /// </value>
        [Parameter] public double? Interval { get; set; }
        /// <summary>
        /// Gets or sets the maximum value for the axis range.
        /// </summary>
        /// <value>
        /// It accepts double values and the default value is null.
        /// </value>
        [Parameter] public Nullable<double> Maximum { get; set; }
        /// <summary>
        /// Gets or sets the minimum value for the axis range.
        /// </summary>
        /// <value>
        /// It accepts double values and the default value is null.
        /// </value>
        [Parameter] public Nullable<double> Minimum { get; set; }
        /// <summary>
        /// Gets or sets a padding type for the numerical axis range.
        /// </summary>
        /// <value>
        /// It accepts the <see cref="T:Syncfusion.Maui.Toolkit.Charts.NumericalPadding" /> value and its default value is <see cref="F:Syncfusion.Maui.Toolkit.Charts.NumericalPadding.Auto" />.
        /// </value>
        [Parameter] public SMTC.NumericalPadding? RangePadding { get; set; }
        /// <summary>
        /// Gets or sets the collection of plot bands to be added to the chart axis.
        /// </summary>
        /// <remarks>
        /// Accepts one or more NumericalPlotBand elements.
        /// </remarks>
        [Parameter] public RenderFragment PlotBands { get; set; }

        public new SMTC.NumericalAxis NativeControl => (SMTC.NumericalAxis)((BindableObject)this).NativeControl;

        protected override SMTC.NumericalAxis CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Interval):
                    if (!Equals(Interval, value))
                    {
                        Interval = (double?)value;
                        NativeControl.Interval = Interval ?? (double)SMTC.NumericalAxis.IntervalProperty.DefaultValue;
                    }
                    break;
                case nameof(Maximum):
                    if (!Equals(Maximum, value))
                    {
                        Maximum = (Nullable<double>)value;
                        NativeControl.Maximum = Maximum;
                    }
                    break;
                case nameof(Minimum):
                    if (!Equals(Minimum, value))
                    {
                        Minimum = (Nullable<double>)value;
                        NativeControl.Minimum = Minimum;
                    }
                    break;
                case nameof(RangePadding):
                    if (!Equals(RangePadding, value))
                    {
                        RangePadding = (SMTC.NumericalPadding?)value;
                        NativeControl.RangePadding = RangePadding ?? (SMTC.NumericalPadding)SMTC.NumericalAxis.RangePaddingProperty.DefaultValue;
                    }
                    break;
                case nameof(PlotBands):
                    PlotBands = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddListContentProperty<SMTC.NumericalAxis, SMTC.NumericalPlotBand>(builder, sequence++, PlotBands, x => x.PlotBands);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
