// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using SMTC = Syncfusion.Maui.Toolkit.Charts;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Charts
{
    /// <summary>
    /// The <see cref="T:Syncfusion.Maui.Toolkit.Charts.PolarLineSeries" /> is a series that displays data in terms of values and angles by using a collection of straight lines. It allows for the visually comparing several quantitative or qualitative aspects of a situation.
    /// </summary>
    public partial class PolarLineSeries : PolarSeries
    {
        static PolarLineSeries()
        {
            RegisterAdditionalHandlers();
        }

        public new SMTC.PolarLineSeries NativeControl => (SMTC.PolarLineSeries)((BindableObject)this).NativeControl;

        protected override SMTC.PolarLineSeries CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
