// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using SMTC = Syncfusion.Maui.Toolkit.Charts;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Charts
{
    /// <summary>
    /// The PolarDataLabelSettings class is used to customize the appearance of polar series data labels.
    /// </summary>
    public partial class PolarDataLabelSettings : ChartDataLabelSettings
    {
        static PolarDataLabelSettings()
        {
            RegisterAdditionalHandlers();
        }

        public new SMTC.PolarDataLabelSettings NativeControl => (SMTC.PolarDataLabelSettings)((BindableObject)this).NativeControl;

        protected override SMTC.PolarDataLabelSettings CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
