// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using SMTC = Syncfusion.Maui.Toolkit.Charts;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Charts
{
    /// <summary>
    /// This class is used to add a rectangle annotation in <see cref="T:Syncfusion.Maui.Toolkit.Charts.SfCartesianChart" />. An instance of this class need to be added to <see cref="P:Syncfusion.Maui.Toolkit.Charts.SfCartesianChart.Annotations" /> collection.
    /// </summary>
    public partial class RectangleAnnotation : ShapeAnnotation
    {
        static RectangleAnnotation()
        {
            RegisterAdditionalHandlers();
        }

        public new SMTC.RectangleAnnotation NativeControl => (SMTC.RectangleAnnotation)((BindableObject)this).NativeControl;

        protected override SMTC.RectangleAnnotation CreateNativeElement() => new();


        static partial void RegisterAdditionalHandlers();
    }
}
