// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.Maui;
using SMTC = Syncfusion.Maui.Toolkit.Charts;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Charts
{
    /// <summary>
    /// The <see cref="T:Syncfusion.Maui.Toolkit.Charts.StackingColumnSeries" /> is a chart type that shows a set of vertical bars stacked on top of each other to represent data point values.
    /// </summary>
    public partial class StackingColumnSeries<T> : StackingSeriesBase<T>
    {
        static StackingColumnSeries()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the value for the corner radius that helps to smooth column edges in stacking column series.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.CornerRadius" /> value, and its default value is null.
        /// </value>
        [Parameter] public CornerRadius? CornerRadius { get; set; }
        /// <summary>
        /// Gets or sets a value to indicate spacing between the segments across the series.
        /// </summary>
        /// <value>
        /// It accepts <c>double</c> values ranging from 0 to 1, where the default value is 0.
        /// </value>
        [Parameter] public double? Spacing { get; set; }
        /// <summary>
        /// Gets or sets a value to change the width of the stacking column segment.
        /// </summary>
        /// <value>
        /// It accepts <c>double</c> values ranging from 0 to 1, where the default value is <c>0.8</c>.
        /// </value>
        [Parameter] public double? Width { get; set; }

        public new SMTC.StackingColumnSeries NativeControl => (SMTC.StackingColumnSeries)((BindableObject)this).NativeControl;

        protected override SMTC.StackingColumnSeries CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(CornerRadius):
                    if (!Equals(CornerRadius, value))
                    {
                        CornerRadius = (CornerRadius?)value;
                        NativeControl.CornerRadius = CornerRadius ?? (CornerRadius)SMTC.StackingColumnSeries.CornerRadiusProperty.DefaultValue;
                    }
                    break;
                case nameof(Spacing):
                    if (!Equals(Spacing, value))
                    {
                        Spacing = (double?)value;
                        NativeControl.Spacing = Spacing ?? (double)SMTC.StackingColumnSeries.SpacingProperty.DefaultValue;
                    }
                    break;
                case nameof(Width):
                    if (!Equals(Width, value))
                    {
                        Width = (double?)value;
                        NativeControl.Width = Width ?? (double)SMTC.StackingColumnSeries.WidthProperty.DefaultValue;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
