// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.Maui.Graphics;
using SMTC = Syncfusion.Maui.Toolkit.Charts;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Charts
{
    /// <summary>
    /// <see cref="T:Syncfusion.Maui.Toolkit.Charts.StackingSeriesBase" /> is a base class for stacking chart series, including <see cref="T:Syncfusion.Maui.Toolkit.Charts.StackingColumnSeries" />,<see cref="T:Syncfusion.Maui.Toolkit.Charts.StackingColumn100Series" />,<see cref="T:Syncfusion.Maui.Toolkit.Charts.StackingLineSeries" />, <see cref="T:Syncfusion.Maui.Toolkit.Charts.StackingLine100Series" />, <see cref="T:Syncfusion.Maui.Toolkit.Charts.StackingAreaSeries" />, and <see cref="T:Syncfusion.Maui.Toolkit.Charts.StackingArea100Series" />.
    /// </summary>
    public abstract partial class StackingSeriesBase : XYDataSeries
    {
        static StackingSeriesBase()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// This property allows for the grouping of series in a stacked chart.
        /// </summary>
        /// <value>
        /// it accept <c>string</c> values and its default value is <c> string.Empty</c>.
        /// </value>
        [Parameter] public string GroupingLabel { get; set; }
        /// <summary>
        /// Gets or sets a value to customize the stroke appearance.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Controls.Brush" /> values and its default value is null.
        /// </value>
        [Parameter] public Color StrokeColor { get; set; }
        /// <summary>
        /// Gets or sets a value to customize the stroke appearance.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Controls.Brush" /> values and its default value is null.
        /// </value>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment Stroke { get; set; }

        public new SMTC.StackingSeriesBase NativeControl => (SMTC.StackingSeriesBase)((BindableObject)this).NativeControl;


        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(GroupingLabel):
                    if (!Equals(GroupingLabel, value))
                    {
                        GroupingLabel = (string)value;
                        NativeControl.GroupingLabel = GroupingLabel;
                    }
                    break;
                case nameof(StrokeColor):
                    if (!Equals(StrokeColor, value))
                    {
                        StrokeColor = (Color)value;
                        NativeControl.Stroke = StrokeColor;
                    }
                    break;
                case nameof(Stroke):
                    Stroke = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddContentProperty<SMTC.StackingSeriesBase>(builder, sequence++, Stroke, (x, value) => x.Stroke = (MC.Brush)value);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
