// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.Maui.Graphics;
using SMTS = Syncfusion.Maui.Toolkit.SunburstChart;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.SunburstChart
{
    /// <summary>
    /// Represents to customize the appearance of sunburst data labels.
    /// </summary>
    public partial class SunburstDataLabelSettings : BlazorBindings.Maui.Elements.BindableObject
    {
        static SunburstDataLabelSettings()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the font attributes for data labels.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Controls.FontAttributes" /> values and the default value is <see cref="F:Microsoft.Maui.Controls.FontAttributes.None" />.
        /// </value>
        [Parameter] public MC.FontAttributes? FontAttributes { get; set; }
        /// <summary>
        /// Gets or sets the font family for data labels.
        /// </summary>
        /// <value>
        /// It accepts string values.
        /// </value>
        [Parameter] public string FontFamily { get; set; }
        /// <summary>
        /// Gets or sets the font size for data labels.
        /// </summary>
        [Parameter] public double? FontSize { get; set; }
        /// <summary>
        /// Gets or sets the label overflow mode for the data label.
        /// </summary>
        /// <value>
        /// The default value is <see cref="F:Syncfusion.Maui.Toolkit.SunburstChart.SunburstLabelOverflowMode.Trim" />.
        /// </value>
        [Parameter] public SMTS.SunburstLabelOverflowMode? OverFlowMode { get; set; }
        /// <summary>
        /// Gets or sets the label rotation mode for data labels.
        /// </summary>
        /// <value>
        /// The default value is <see cref="F:Syncfusion.Maui.Toolkit.SunburstChart.SunburstLabelRotationMode.Angle" />.
        /// </value>
        [Parameter] public SMTS.SunburstLabelRotationMode? RotationMode { get; set; }
        /// <summary>
        /// Gets or sets the color for the data labels.
        /// </summary>
        [Parameter] public Color TextColor { get; set; }

        public new SMTS.SunburstDataLabelSettings NativeControl => (SMTS.SunburstDataLabelSettings)((BindableObject)this).NativeControl;

        protected override SMTS.SunburstDataLabelSettings CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(FontAttributes):
                    if (!Equals(FontAttributes, value))
                    {
                        FontAttributes = (MC.FontAttributes?)value;
                        NativeControl.FontAttributes = FontAttributes ?? (MC.FontAttributes)SMTS.SunburstDataLabelSettings.FontAttributesProperty.DefaultValue;
                    }
                    break;
                case nameof(FontFamily):
                    if (!Equals(FontFamily, value))
                    {
                        FontFamily = (string)value;
                        NativeControl.FontFamily = FontFamily;
                    }
                    break;
                case nameof(FontSize):
                    if (!Equals(FontSize, value))
                    {
                        FontSize = (double?)value;
                        NativeControl.FontSize = FontSize ?? (double)SMTS.SunburstDataLabelSettings.FontSizeProperty.DefaultValue;
                    }
                    break;
                case nameof(OverFlowMode):
                    if (!Equals(OverFlowMode, value))
                    {
                        OverFlowMode = (SMTS.SunburstLabelOverflowMode?)value;
                        NativeControl.OverFlowMode = OverFlowMode ?? (SMTS.SunburstLabelOverflowMode)SMTS.SunburstDataLabelSettings.OverFlowModeProperty.DefaultValue;
                    }
                    break;
                case nameof(RotationMode):
                    if (!Equals(RotationMode, value))
                    {
                        RotationMode = (SMTS.SunburstLabelRotationMode?)value;
                        NativeControl.RotationMode = RotationMode ?? (SMTS.SunburstLabelRotationMode)SMTS.SunburstDataLabelSettings.RotationModeProperty.DefaultValue;
                    }
                    break;
                case nameof(TextColor):
                    if (!Equals(TextColor, value))
                    {
                        TextColor = (Color)value;
                        NativeControl.TextColor = TextColor;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
