// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.Maui;
using Microsoft.Maui.Graphics;
using SMTS = Syncfusion.Maui.Toolkit.SparkCharts;
using System.Collections.Generic;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.SparkCharts
{
    /// <summary>
    /// Represents the base class for all Spark Charts and provides common behaviors and control flow.
    /// </summary>
    public abstract partial class SfSparkChart<T> : BlazorBindings.Maui.Elements.View
    {
        static SfSparkChart()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the value to configure axis orgin.
        /// </summary>
        [Parameter] public double? AxisOrigin { get; set; }
        /// <summary>
        /// Gets or sets the collection used to generate the _content of the chart.
        /// </summary>
        [Parameter] public IList<T> ItemsSource { get; set; }
        /// <summary>
        /// Gets or sets the maximum value for the Y-axis.
        /// </summary>
        [Parameter] public double? MaximumYValue { get; set; }
        /// <summary>
        /// Gets or sets the minimum value for the Y-axis.
        /// </summary>
        [Parameter] public double? MinimumYValue { get; set; }
        /// <summary>
        /// Gets or sets the padding for the chart line, area, column or win-loss.
        /// </summary>
        [Parameter] public Thickness? Padding { get; set; }
        /// <summary>
        /// Gets or sets the flag to visible axis.
        /// </summary>
        [Parameter] public bool? ShowAxis { get; set; }
        /// <summary>
        /// Gets or sets the brush used to draw the stroke for the chart line, area, column or win-loss.
        /// </summary>
        [Parameter] public Color StrokeColor { get; set; }
        /// <summary>
        /// Gets or sets the path to the property used for Y-axis values.
        /// </summary>
        [Parameter] public string YBindingPath { get; set; }
        /// <summary>
        /// Gets or sets the line style for axis.
        /// </summary>
        /// <remarks>
        /// Accepts single SparkChartLineStyle element.
        /// </remarks>
        [Parameter] public RenderFragment AxisLineStyle { get; set; }
        /// <summary>
        /// Gets or sets the brush used to draw the stroke for the chart line, area, column or win-loss.
        /// </summary>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment Stroke { get; set; }

        public new SMTS.SfSparkChart NativeControl => (SMTS.SfSparkChart)((BindableObject)this).NativeControl;


        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(AxisOrigin):
                    if (!Equals(AxisOrigin, value))
                    {
                        AxisOrigin = (double?)value;
                        NativeControl.AxisOrigin = AxisOrigin ?? (double)SMTS.SfSparkChart.AxisOriginProperty.DefaultValue;
                    }
                    break;
                case nameof(ItemsSource):
                    if (!Equals(ItemsSource, value))
                    {
                        ItemsSource = (IList<T>)value;
                        NativeControl.ItemsSource = ItemsSource;
                    }
                    break;
                case nameof(MaximumYValue):
                    if (!Equals(MaximumYValue, value))
                    {
                        MaximumYValue = (double?)value;
                        NativeControl.MaximumYValue = MaximumYValue ?? (double)SMTS.SfSparkChart.MaximumYValueProperty.DefaultValue;
                    }
                    break;
                case nameof(MinimumYValue):
                    if (!Equals(MinimumYValue, value))
                    {
                        MinimumYValue = (double?)value;
                        NativeControl.MinimumYValue = MinimumYValue ?? (double)SMTS.SfSparkChart.MinimumYValueProperty.DefaultValue;
                    }
                    break;
                case nameof(Padding):
                    if (!Equals(Padding, value))
                    {
                        Padding = (Thickness?)value;
                        NativeControl.Padding = Padding ?? (Thickness)SMTS.SfSparkChart.PaddingProperty.DefaultValue;
                    }
                    break;
                case nameof(ShowAxis):
                    if (!Equals(ShowAxis, value))
                    {
                        ShowAxis = (bool?)value;
                        NativeControl.ShowAxis = ShowAxis ?? (bool)SMTS.SfSparkChart.ShowAxisProperty.DefaultValue;
                    }
                    break;
                case nameof(StrokeColor):
                    if (!Equals(StrokeColor, value))
                    {
                        StrokeColor = (Color)value;
                        NativeControl.Stroke = StrokeColor;
                    }
                    break;
                case nameof(YBindingPath):
                    if (!Equals(YBindingPath, value))
                    {
                        YBindingPath = (string)value;
                        NativeControl.YBindingPath = YBindingPath;
                    }
                    break;
                case nameof(AxisLineStyle):
                    AxisLineStyle = (RenderFragment)value;
                    break;
                case nameof(Stroke):
                    Stroke = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddContentProperty<SMTS.SfSparkChart>(builder, sequence++, AxisLineStyle, (x, value) => x.AxisLineStyle = (SMTS.SparkChartLineStyle)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTS.SfSparkChart>(builder, sequence++, Stroke, (x, value) => x.Stroke = (MC.Brush)value);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
