// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.Maui;
using Microsoft.Maui.Graphics;
using SMTS = Syncfusion.Maui.Toolkit.SparkCharts;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.SparkCharts
{
    /// <summary>
    /// Represents the label style for SparkChart trackball labels.
    /// </summary>
    public partial class SparkChartLabelStyle : BlazorBindings.Maui.Elements.Element
    {
        static SparkChartLabelStyle()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets a value to customize the appearance of the label's background.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Controls.Brush" /> values and the default value is <see cref="F:Microsoft.Maui.Graphics.Colors.Black" />.
        /// </value>
        [Parameter] public Color BackgroundColor { get; set; }
        /// <summary>
        /// Gets or sets a value that indicates the font attributes of the label.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Controls.FontAttributes" /> values and the default value is <see cref="F:Microsoft.Maui.Controls.FontAttributes.None" />.
        /// </value>
        [Parameter] public MC.FontAttributes? FontAttributes { get; set; }
        /// <summary>
        /// Gets or sets a value that indicates the font family of the label.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:System.String" /> values and the default value is <see cref="F:System.String.Empty" />.
        /// </value>
        [Parameter] public string FontFamily { get; set; }
        /// <summary>
        /// Gets or sets a value that indicates the label's font size.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:System.Double" /> values and the default value is 12.
        /// </value>
        [Parameter] public double? FontSize { get; set; }
        /// <summary>
        /// Gets or sets a value to customize the label's format.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:System.String" /> values and the default value is <see cref="F:System.String.Empty" />.
        /// </value>
        [Parameter] public string LabelFormat { get; set; }
        /// <summary>
        /// Gets or sets a value that indicates the margin of the label.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Thickness" /> values and the default value is 4.
        /// </value>
        [Parameter] public Thickness? Margin { get; set; }
        /// <summary>
        /// Gets or sets a value to customize the outer stroke appearance of the label.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Controls.Brush" /> values and the default value is <see cref="P:Microsoft.Maui.Controls.Brush.Transparent" />.
        /// </value>
        [Parameter] public Color StrokeColor { get; set; }
        /// <summary>
        /// Gets or sets a value that indicates the stroke thickness of the label.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:System.Double" /> values and the default value is 0.
        /// </value>
        [Parameter] public double? StrokeWidth { get; set; }
        /// <summary>
        /// Gets or sets a value to customize the appearance of the label's text color.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Graphics.Color" /> values and the default value is <see cref="F:Microsoft.Maui.Graphics.Colors.White" />.
        /// </value>
        [Parameter] public Color TextColor { get; set; }
        /// <summary>
        /// Gets or sets a value to customize the appearance of the label's background.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Controls.Brush" /> values and the default value is <see cref="F:Microsoft.Maui.Graphics.Colors.Black" />.
        /// </value>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment Background { get; set; }
        /// <summary>
        /// Gets or sets a value to customize the outer stroke appearance of the label.
        /// </summary>
        /// <value>
        /// It accepts <see cref="T:Microsoft.Maui.Controls.Brush" /> values and the default value is <see cref="P:Microsoft.Maui.Controls.Brush.Transparent" />.
        /// </value>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment Stroke { get; set; }

        public new SMTS.SparkChartLabelStyle NativeControl => (SMTS.SparkChartLabelStyle)((BindableObject)this).NativeControl;

        protected override SMTS.SparkChartLabelStyle CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(BackgroundColor):
                    if (!Equals(BackgroundColor, value))
                    {
                        BackgroundColor = CastParameter<Color>(value, name);
                        NativeControl.Background = BackgroundColor;
                    }
                    break;
                case nameof(FontAttributes):
                    if (!Equals(FontAttributes, value))
                    {
                        FontAttributes = CastParameter<MC.FontAttributes?>(value, name);
                        NativeControl.FontAttributes = FontAttributes ?? (MC.FontAttributes)SMTS.SparkChartLabelStyle.FontAttributesProperty.DefaultValue;
                    }
                    break;
                case nameof(FontFamily):
                    if (!Equals(FontFamily, value))
                    {
                        FontFamily = CastParameter<string>(value, name);
                        NativeControl.FontFamily = FontFamily;
                    }
                    break;
                case nameof(FontSize):
                    if (!Equals(FontSize, value))
                    {
                        FontSize = CastParameter<double?>(value, name);
                        NativeControl.FontSize = FontSize ?? (double)SMTS.SparkChartLabelStyle.FontSizeProperty.DefaultValue;
                    }
                    break;
                case nameof(LabelFormat):
                    if (!Equals(LabelFormat, value))
                    {
                        LabelFormat = CastParameter<string>(value, name);
                        NativeControl.LabelFormat = LabelFormat;
                    }
                    break;
                case nameof(Margin):
                    if (!Equals(Margin, value))
                    {
                        Margin = CastParameter<Thickness?>(value, name);
                        NativeControl.Margin = Margin ?? (Thickness)SMTS.SparkChartLabelStyle.MarginProperty.DefaultValue;
                    }
                    break;
                case nameof(StrokeColor):
                    if (!Equals(StrokeColor, value))
                    {
                        StrokeColor = CastParameter<Color>(value, name);
                        NativeControl.Stroke = StrokeColor;
                    }
                    break;
                case nameof(StrokeWidth):
                    if (!Equals(StrokeWidth, value))
                    {
                        StrokeWidth = CastParameter<double?>(value, name);
                        NativeControl.StrokeWidth = StrokeWidth ?? (double)SMTS.SparkChartLabelStyle.StrokeWidthProperty.DefaultValue;
                    }
                    break;
                case nameof(TextColor):
                    if (!Equals(TextColor, value))
                    {
                        TextColor = CastParameter<Color>(value, name);
                        NativeControl.TextColor = TextColor;
                    }
                    break;
                case nameof(Background):
                    Background = CastParameter<RenderFragment>(value, name);
                    break;
                case nameof(Stroke):
                    Stroke = CastParameter<RenderFragment>(value, name);
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddContentProperty<SMTS.SparkChartLabelStyle>(builder, sequence++, Background, (x, value) => x.Background = (MC.Brush)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTS.SparkChartLabelStyle>(builder, sequence++, Stroke, (x, value) => x.Stroke = (MC.Brush)value);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
