// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.Maui;
using Microsoft.Maui.Graphics;
using SMTP = Syncfusion.Maui.Toolkit.Popup;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Popup
{
    /// <summary>
    /// Represents the style of <see cref="T:Syncfusion.Maui.Toolkit.Popup.SfPopup" />.
    /// </summary>
    public partial class PopupStyle : BlazorBindings.Maui.Elements.Element
    {
        static PopupStyle()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the background color of accept button in the footer.
        /// </summary>
        [Parameter] public Color AcceptButtonBackgroundColor { get; set; }
        /// <summary>
        /// Gets or sets the foreground color of accept button in the footer.
        /// </summary>
        [Parameter] public Color AcceptButtonTextColor { get; set; }
        /// <summary>
        /// Gets or sets a value that indicates the intensity of the blur effect in the overlay.
        /// </summary>
        [Parameter] public SMTP.PopupBlurIntensity? BlurIntensity { get; set; }
        /// <summary>
        /// Gets or sets the blur radius of the blur effect applied to the overlay when the <see cref="P:Syncfusion.Maui.Toolkit.Popup.PopupStyle.BlurIntensity" /> is <see cref="F:Syncfusion.Maui.Toolkit.Popup.PopupBlurIntensity.Custom" />. Does not have any effect when <see cref="P:Syncfusion.Maui.Toolkit.Popup.PopupStyle.BlurIntensity" /> has values other than <see cref="F:Syncfusion.Maui.Toolkit.Popup.PopupBlurIntensity.Custom" />.
        /// </summary>
        [Parameter] public float? BlurRadius { get; set; }
        /// <summary>
        /// Gets or sets the image to be placed in the header close button for the <see cref="T:Syncfusion.Maui.Toolkit.Popup.PopupView" />.
        /// </summary>
        [Parameter] public MC.ImageSource CloseButtonIcon { get; set; }
        /// <summary>
        /// Gets or sets the color of the close icon displayed in the <see cref="T:Syncfusion.Maui.Toolkit.Popup.SfPopup" />.
        /// </summary>
        [Parameter] public Color CloseIconColor { get; set; }
        /// <summary>
        /// Gets or sets the corner radius for the <see cref="T:Syncfusion.Maui.Toolkit.Popup.PopupView" />.
        /// </summary>
        [Parameter] public CornerRadius? CornerRadius { get; set; }
        /// <summary>
        /// Gets or sets the background color of decline button in the footer.
        /// </summary>
        [Parameter] public Color DeclineButtonBackgroundColor { get; set; }
        /// <summary>
        /// Gets or sets the foreground color of decline button in the footer.
        /// </summary>
        [Parameter] public Color DeclineButtonTextColor { get; set; }
        /// <summary>
        /// Gets or sets the background color of the <see cref="T:Syncfusion.Maui.Toolkit.Popup.SfPopup" /> footer.
        /// </summary>
        [Parameter] public Color FooterBackgroundColor { get; set; }
        /// <summary>
        /// Gets or sets the corner radius of the accept and decline buttons in the footer. The default value is 20.
        /// </summary>
        [Parameter] public CornerRadius? FooterButtonCornerRadius { get; set; }
        /// <summary>
        /// Gets or sets the font attribute to be applied for the footer buttons.
        /// </summary>
        [Parameter] public MC.FontAttributes? FooterFontAttribute { get; set; }
        /// <summary>
        /// Gets or sets the font style to be applied for the footer buttons.
        /// </summary>
        [Parameter] public string FooterFontFamily { get; set; }
        /// <summary>
        /// Gets or sets the font size of the footer buttons.
        /// </summary>
        [Parameter] public double? FooterFontSize { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether a drop shadow is displayed around the Popupview. The default value is true.
        /// </summary>
        [Parameter] public bool? HasShadow { get; set; }
        /// <summary>
        /// Gets or sets the background color to be applied for the header.
        /// </summary>
        [Parameter] public Color HeaderBackgroundColor { get; set; }
        /// <summary>
        /// Gets or sets the font attribute to be applied for the header title.
        /// </summary>
        [Parameter] public MC.FontAttributes? HeaderFontAttribute { get; set; }
        /// <summary>
        /// Gets or sets the font style to be applied for the header title.
        /// </summary>
        [Parameter] public string HeaderFontFamily { get; set; }
        /// <summary>
        /// Gets or sets the font size of the header title.
        /// </summary>
        [Parameter] public double? HeaderFontSize { get; set; }
        /// <summary>
        /// Gets or sets the text alignment of the header.
        /// </summary>
        [Parameter] public TextAlignment? HeaderTextAlignment { get; set; }
        /// <summary>
        /// Gets or sets the text color to be applied for the header title.
        /// </summary>
        [Parameter] public Color HeaderTextColor { get; set; }
        /// <summary>
        /// Gets or sets the background color of content.
        /// </summary>
        [Parameter] public Color MessageBackgroundColor { get; set; }
        /// <summary>
        /// Gets or sets the font attribute to be applied for the content.
        /// </summary>
        [Parameter] public MC.FontAttributes? MessageFontAttribute { get; set; }
        /// <summary>
        /// Gets or sets the font style to be applied for the content.
        /// </summary>
        [Parameter] public string MessageFontFamily { get; set; }
        /// <summary>
        /// Gets or sets the font size of the content.
        /// </summary>
        [Parameter] public double? MessageFontSize { get; set; }
        /// <summary>
        /// Gets or sets the text alignment of the content.
        /// </summary>
        [Parameter] public TextAlignment? MessageTextAlignment { get; set; }
        /// <summary>
        /// Gets or sets the foreground color of content.
        /// </summary>
        [Parameter] public Color MessageTextColor { get; set; }
        /// <summary>
        /// Gets or sets the overlay color when PopupView is displayed.
        /// </summary>
        /// <value>
        /// The overlay color displayed when the PopupView is shown. Default is transparent.
        /// </value>
        [Parameter] public Color OverlayColorColor { get; set; }
        /// <summary>
        /// Gets or sets the background color of the PopupView.
        /// </summary>
        [Parameter] public Color PopupBackgroundColor { get; set; }
        /// <summary>
        /// Gets or sets the border color for the <see cref="T:Syncfusion.Maui.Toolkit.Popup.PopupView" />.
        /// </summary>
        [Parameter] public Color Stroke { get; set; }
        /// <summary>
        /// Gets or sets the border thickness for the <see cref="T:Syncfusion.Maui.Toolkit.Popup.PopupView" />.
        /// </summary>
        [Parameter] public int? StrokeThickness { get; set; }
        /// <summary>
        /// Gets or sets the background color of accept button in the footer.
        /// </summary>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment AcceptButtonBackground { get; set; }
        /// <summary>
        /// Gets or sets the background color of decline button in the footer.
        /// </summary>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment DeclineButtonBackground { get; set; }
        /// <summary>
        /// Gets or sets the background color of the <see cref="T:Syncfusion.Maui.Toolkit.Popup.SfPopup" /> footer.
        /// </summary>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment FooterBackground { get; set; }
        /// <summary>
        /// Gets or sets the background color to be applied for the header.
        /// </summary>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment HeaderBackground { get; set; }
        /// <summary>
        /// Gets or sets the background color of content.
        /// </summary>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment MessageBackground { get; set; }
        /// <summary>
        /// Gets or sets the overlay color when PopupView is displayed.
        /// </summary>
        /// <value>
        /// The overlay color displayed when the PopupView is shown. Default is transparent.
        /// </value>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment OverlayColor { get; set; }
        /// <summary>
        /// Gets or sets the background color of the PopupView.
        /// </summary>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment PopupBackground { get; set; }

        public new SMTP.PopupStyle NativeControl => (SMTP.PopupStyle)((BindableObject)this).NativeControl;

        protected override SMTP.PopupStyle CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(AcceptButtonBackgroundColor):
                    if (!Equals(AcceptButtonBackgroundColor, value))
                    {
                        AcceptButtonBackgroundColor = (Color)value;
                        NativeControl.AcceptButtonBackground = AcceptButtonBackgroundColor;
                    }
                    break;
                case nameof(AcceptButtonTextColor):
                    if (!Equals(AcceptButtonTextColor, value))
                    {
                        AcceptButtonTextColor = (Color)value;
                        NativeControl.AcceptButtonTextColor = AcceptButtonTextColor;
                    }
                    break;
                case nameof(BlurIntensity):
                    if (!Equals(BlurIntensity, value))
                    {
                        BlurIntensity = (SMTP.PopupBlurIntensity?)value;
                        NativeControl.BlurIntensity = BlurIntensity ?? (SMTP.PopupBlurIntensity)SMTP.PopupStyle.BlurIntensityProperty.DefaultValue;
                    }
                    break;
                case nameof(BlurRadius):
                    if (!Equals(BlurRadius, value))
                    {
                        BlurRadius = (float?)value;
                        NativeControl.BlurRadius = BlurRadius ?? (float)SMTP.PopupStyle.BlurRadiusProperty.DefaultValue;
                    }
                    break;
                case nameof(CloseButtonIcon):
                    if (!Equals(CloseButtonIcon, value))
                    {
                        CloseButtonIcon = (MC.ImageSource)value;
                        NativeControl.CloseButtonIcon = CloseButtonIcon;
                    }
                    break;
                case nameof(CloseIconColor):
                    if (!Equals(CloseIconColor, value))
                    {
                        CloseIconColor = (Color)value;
                        NativeControl.CloseIconColor = CloseIconColor;
                    }
                    break;
                case nameof(CornerRadius):
                    if (!Equals(CornerRadius, value))
                    {
                        CornerRadius = (CornerRadius?)value;
                        NativeControl.CornerRadius = CornerRadius ?? (CornerRadius)SMTP.PopupStyle.CornerRadiusProperty.DefaultValue;
                    }
                    break;
                case nameof(DeclineButtonBackgroundColor):
                    if (!Equals(DeclineButtonBackgroundColor, value))
                    {
                        DeclineButtonBackgroundColor = (Color)value;
                        NativeControl.DeclineButtonBackground = DeclineButtonBackgroundColor;
                    }
                    break;
                case nameof(DeclineButtonTextColor):
                    if (!Equals(DeclineButtonTextColor, value))
                    {
                        DeclineButtonTextColor = (Color)value;
                        NativeControl.DeclineButtonTextColor = DeclineButtonTextColor;
                    }
                    break;
                case nameof(FooterBackgroundColor):
                    if (!Equals(FooterBackgroundColor, value))
                    {
                        FooterBackgroundColor = (Color)value;
                        NativeControl.FooterBackground = FooterBackgroundColor;
                    }
                    break;
                case nameof(FooterButtonCornerRadius):
                    if (!Equals(FooterButtonCornerRadius, value))
                    {
                        FooterButtonCornerRadius = (CornerRadius?)value;
                        NativeControl.FooterButtonCornerRadius = FooterButtonCornerRadius ?? (CornerRadius)SMTP.PopupStyle.FooterButtonCornerRadiusProperty.DefaultValue;
                    }
                    break;
                case nameof(FooterFontAttribute):
                    if (!Equals(FooterFontAttribute, value))
                    {
                        FooterFontAttribute = (MC.FontAttributes?)value;
                        NativeControl.FooterFontAttribute = FooterFontAttribute ?? (MC.FontAttributes)SMTP.PopupStyle.FooterFontAttributeProperty.DefaultValue;
                    }
                    break;
                case nameof(FooterFontFamily):
                    if (!Equals(FooterFontFamily, value))
                    {
                        FooterFontFamily = (string)value;
                        NativeControl.FooterFontFamily = FooterFontFamily;
                    }
                    break;
                case nameof(FooterFontSize):
                    if (!Equals(FooterFontSize, value))
                    {
                        FooterFontSize = (double?)value;
                        NativeControl.FooterFontSize = FooterFontSize ?? (double)SMTP.PopupStyle.FooterFontSizeProperty.DefaultValue;
                    }
                    break;
                case nameof(HasShadow):
                    if (!Equals(HasShadow, value))
                    {
                        HasShadow = (bool?)value;
                        NativeControl.HasShadow = HasShadow ?? (bool)SMTP.PopupStyle.HasShadowProperty.DefaultValue;
                    }
                    break;
                case nameof(HeaderBackgroundColor):
                    if (!Equals(HeaderBackgroundColor, value))
                    {
                        HeaderBackgroundColor = (Color)value;
                        NativeControl.HeaderBackground = HeaderBackgroundColor;
                    }
                    break;
                case nameof(HeaderFontAttribute):
                    if (!Equals(HeaderFontAttribute, value))
                    {
                        HeaderFontAttribute = (MC.FontAttributes?)value;
                        NativeControl.HeaderFontAttribute = HeaderFontAttribute ?? (MC.FontAttributes)SMTP.PopupStyle.HeaderFontAttributeProperty.DefaultValue;
                    }
                    break;
                case nameof(HeaderFontFamily):
                    if (!Equals(HeaderFontFamily, value))
                    {
                        HeaderFontFamily = (string)value;
                        NativeControl.HeaderFontFamily = HeaderFontFamily;
                    }
                    break;
                case nameof(HeaderFontSize):
                    if (!Equals(HeaderFontSize, value))
                    {
                        HeaderFontSize = (double?)value;
                        NativeControl.HeaderFontSize = HeaderFontSize ?? (double)SMTP.PopupStyle.HeaderFontSizeProperty.DefaultValue;
                    }
                    break;
                case nameof(HeaderTextAlignment):
                    if (!Equals(HeaderTextAlignment, value))
                    {
                        HeaderTextAlignment = (TextAlignment?)value;
                        NativeControl.HeaderTextAlignment = HeaderTextAlignment ?? (TextAlignment)SMTP.PopupStyle.HeaderTextAlignmentProperty.DefaultValue;
                    }
                    break;
                case nameof(HeaderTextColor):
                    if (!Equals(HeaderTextColor, value))
                    {
                        HeaderTextColor = (Color)value;
                        NativeControl.HeaderTextColor = HeaderTextColor;
                    }
                    break;
                case nameof(MessageBackgroundColor):
                    if (!Equals(MessageBackgroundColor, value))
                    {
                        MessageBackgroundColor = (Color)value;
                        NativeControl.MessageBackground = MessageBackgroundColor;
                    }
                    break;
                case nameof(MessageFontAttribute):
                    if (!Equals(MessageFontAttribute, value))
                    {
                        MessageFontAttribute = (MC.FontAttributes?)value;
                        NativeControl.MessageFontAttribute = MessageFontAttribute ?? (MC.FontAttributes)SMTP.PopupStyle.MessageFontAttributeProperty.DefaultValue;
                    }
                    break;
                case nameof(MessageFontFamily):
                    if (!Equals(MessageFontFamily, value))
                    {
                        MessageFontFamily = (string)value;
                        NativeControl.MessageFontFamily = MessageFontFamily;
                    }
                    break;
                case nameof(MessageFontSize):
                    if (!Equals(MessageFontSize, value))
                    {
                        MessageFontSize = (double?)value;
                        NativeControl.MessageFontSize = MessageFontSize ?? (double)SMTP.PopupStyle.MessageFontSizeProperty.DefaultValue;
                    }
                    break;
                case nameof(MessageTextAlignment):
                    if (!Equals(MessageTextAlignment, value))
                    {
                        MessageTextAlignment = (TextAlignment?)value;
                        NativeControl.MessageTextAlignment = MessageTextAlignment ?? (TextAlignment)SMTP.PopupStyle.MessageTextAlignmentProperty.DefaultValue;
                    }
                    break;
                case nameof(MessageTextColor):
                    if (!Equals(MessageTextColor, value))
                    {
                        MessageTextColor = (Color)value;
                        NativeControl.MessageTextColor = MessageTextColor;
                    }
                    break;
                case nameof(OverlayColorColor):
                    if (!Equals(OverlayColorColor, value))
                    {
                        OverlayColorColor = (Color)value;
                        NativeControl.OverlayColor = OverlayColorColor;
                    }
                    break;
                case nameof(PopupBackgroundColor):
                    if (!Equals(PopupBackgroundColor, value))
                    {
                        PopupBackgroundColor = (Color)value;
                        NativeControl.PopupBackground = PopupBackgroundColor;
                    }
                    break;
                case nameof(Stroke):
                    if (!Equals(Stroke, value))
                    {
                        Stroke = (Color)value;
                        NativeControl.Stroke = Stroke;
                    }
                    break;
                case nameof(StrokeThickness):
                    if (!Equals(StrokeThickness, value))
                    {
                        StrokeThickness = (int?)value;
                        NativeControl.StrokeThickness = StrokeThickness ?? (int)SMTP.PopupStyle.StrokeThicknessProperty.DefaultValue;
                    }
                    break;
                case nameof(AcceptButtonBackground):
                    AcceptButtonBackground = (RenderFragment)value;
                    break;
                case nameof(DeclineButtonBackground):
                    DeclineButtonBackground = (RenderFragment)value;
                    break;
                case nameof(FooterBackground):
                    FooterBackground = (RenderFragment)value;
                    break;
                case nameof(HeaderBackground):
                    HeaderBackground = (RenderFragment)value;
                    break;
                case nameof(MessageBackground):
                    MessageBackground = (RenderFragment)value;
                    break;
                case nameof(OverlayColor):
                    OverlayColor = (RenderFragment)value;
                    break;
                case nameof(PopupBackground):
                    PopupBackground = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PopupStyle>(builder, sequence++, AcceptButtonBackground, (x, value) => x.AcceptButtonBackground = (MC.Brush)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PopupStyle>(builder, sequence++, DeclineButtonBackground, (x, value) => x.DeclineButtonBackground = (MC.Brush)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PopupStyle>(builder, sequence++, FooterBackground, (x, value) => x.FooterBackground = (MC.Brush)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PopupStyle>(builder, sequence++, HeaderBackground, (x, value) => x.HeaderBackground = (MC.Brush)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PopupStyle>(builder, sequence++, MessageBackground, (x, value) => x.MessageBackground = (MC.Brush)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PopupStyle>(builder, sequence++, OverlayColor, (x, value) => x.OverlayColor = (MC.Brush)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PopupStyle>(builder, sequence++, PopupBackground, (x, value) => x.PopupBackground = (MC.Brush)value);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
