// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using SMTI = Syncfusion.Maui.Toolkit.Internals;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Internals
{
    /// <summary>
    /// Helper class to override native methods.
    /// </summary>
    public abstract partial class PullToRefreshBase : BlazorBindings.Maui.Elements.Syncfusion.Toolkit.SfView
    {
        static PullToRefreshBase()
        {
            RegisterAdditionalHandlers();
        }

        public new SMTI.PullToRefreshBase NativeControl => (SMTI.PullToRefreshBase)((BindableObject)this).NativeControl;



        static partial void RegisterAdditionalHandlers();
    }
}
