// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.Maui;
using Microsoft.Maui.Graphics;
using SMTP = Syncfusion.Maui.Toolkit.Picker;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Picker
{
    /// <summary>
    /// Represents a class which is used to customize all the properties of selection view of the SfPicker.
    /// </summary>
    public partial class PickerSelectionView : BlazorBindings.Maui.Elements.Element
    {
        static PickerSelectionView()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the background of the selection view in SfPicker.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerSelectionView.Background" /> is SolidColorBrush(Color.FromArgb("#6750A4")).
        /// </value>
        [Parameter] public Color BackgroundColor { get; set; }
        /// <summary>
        /// Gets or sets the corner radius of the selection view in SfPicker.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerSelectionView.CornerRadius" /> is 20.
        /// </value>
        [Parameter] public CornerRadius? CornerRadius { get; set; }
        /// <summary>
        /// Gets or sets the padding value of the selection view in SfPicker.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerSelectionView.Padding" /> is new Thickness(5, 2).
        /// </value>
        [Parameter] public Thickness? Padding { get; set; }
        /// <summary>
        /// Gets or sets the stroke color of the selection view in SfPicker.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerSelectionView.Stroke" /> is Colors.Transparent.
        /// </value>
        [Parameter] public Color Stroke { get; set; }
        /// <summary>
        /// Gets or sets the background of the selection view in SfPicker.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerSelectionView.Background" /> is SolidColorBrush(Color.FromArgb("#6750A4")).
        /// </value>
        /// <remarks>
        /// Accepts single Brush element.
        /// </remarks>
        [Parameter] public RenderFragment Background { get; set; }

        public new SMTP.PickerSelectionView NativeControl => (SMTP.PickerSelectionView)((BindableObject)this).NativeControl;

        protected override SMTP.PickerSelectionView CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(BackgroundColor):
                    if (!Equals(BackgroundColor, value))
                    {
                        BackgroundColor = (Color)value;
                        NativeControl.Background = BackgroundColor;
                    }
                    break;
                case nameof(CornerRadius):
                    if (!Equals(CornerRadius, value))
                    {
                        CornerRadius = (CornerRadius?)value;
                        NativeControl.CornerRadius = CornerRadius ?? (CornerRadius)SMTP.PickerSelectionView.CornerRadiusProperty.DefaultValue;
                    }
                    break;
                case nameof(Padding):
                    if (!Equals(Padding, value))
                    {
                        Padding = (Thickness?)value;
                        NativeControl.Padding = Padding ?? (Thickness)SMTP.PickerSelectionView.PaddingProperty.DefaultValue;
                    }
                    break;
                case nameof(Stroke):
                    if (!Equals(Stroke, value))
                    {
                        Stroke = (Color)value;
                        NativeControl.Stroke = Stroke;
                    }
                    break;
                case nameof(Background):
                    Background = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PickerSelectionView>(builder, sequence++, Background, (x, value) => x.Background = (MC.Brush)value);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
