// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using Microsoft.Maui.Graphics;
using SMTP = Syncfusion.Maui.Toolkit.Picker;
using System;
using System.ComponentModel;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.Picker
{
    /// <summary>
    /// Class that represents and render the picker control,
    /// </summary>
    public abstract partial class PickerBase : BlazorBindings.Maui.Elements.Syncfusion.Toolkit.SfView
    {
        static PickerBase()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets the value of column divider color in SfPicker. This property can be used to customize the column divider color in Picker.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerBase.ColumnDividerColor" /> is "#CAC4D0".
        /// </value>
        [Parameter] public Color ColumnDividerColor { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether the picker can perform looping.
        /// </summary>
        [Parameter] public bool? EnableLooping { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether the picker is open or not.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerBase.IsOpen" /> is "False".
        /// </value>
        [Parameter] public bool? IsOpen { get; set; }
        /// <summary>
        /// Gets or sets the value to specify the item height of picker view on Picker.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerBase.ItemHeight" /> is 40d.
        /// </value>
        [Parameter] public double? ItemHeight { get; set; }
        /// <summary>
        /// Gets or sets the mode of the picker.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerBase.Mode" /> is <see cref="F:Syncfusion.Maui.Toolkit.Picker.PickerMode.Default" />.
        /// </value>
        [Parameter] public SMTP.PickerMode? Mode { get; set; }
        /// <summary>
        /// Gets or sets the height of the popup in the picker.
        /// </summary>
        [Parameter] public double? PopupHeight { get; set; }
        /// <summary>
        /// Gets or sets the width of the popup in the picker.
        /// </summary>
        [Parameter] public double? PopupWidth { get; set; }
        /// <summary>
        /// Gets or sets the relative position of the picker popup.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerBase.RelativePosition" /> is <see cref="F:Syncfusion.Maui.Toolkit.Picker.PickerRelativePosition.AlignTop" />.
        /// </value>
        [Parameter] public SMTP.PickerRelativePosition? RelativePosition { get; set; }
        /// <summary>
        /// Gets or sets the picker selected text style in Picker.
        /// </summary>
        [Parameter] public SMTP.PickerTextStyle SelectedTextStyle { get; set; }
        /// <summary>
        /// Gets or sets the text display mode of the picker.
        /// </summary>
        /// <value>
        /// The default value of <see cref="P:Syncfusion.Maui.Toolkit.Picker.PickerBase.TextDisplayMode" /> is <see cref="F:Syncfusion.Maui.Toolkit.Picker.PickerTextDisplayMode.Default" />.
        /// </value>
        [Parameter] public SMTP.PickerTextDisplayMode? TextDisplayMode { get; set; }
        /// <summary>
        /// Gets or sets the column header template or template selector for picker column header.
        /// </summary>
        [Parameter] public RenderFragment ColumnHeaderTemplate { get; set; }
        /// <summary>
        /// Gets or sets the footer template or template selector for picker footer.
        /// </summary>
        [Parameter] public RenderFragment FooterTemplate { get; set; }
        /// <summary>
        /// Gets or sets the value of footer view. This property can be used to customize the Footer in Picker.
        /// </summary>
        /// <remarks>
        /// Accepts single PickerFooterView element.
        /// </remarks>
        [Parameter] public RenderFragment FooterView { get; set; }
        /// <summary>
        /// Gets or sets the header template or template selector for picker header
        /// </summary>
        [Parameter] public RenderFragment HeaderTemplate { get; set; }
        /// <summary>
        /// Gets or sets the view relative to which the picker dialog should be displayed based on the RelativePosition. <seealso cref="P:Syncfusion.Maui.Toolkit.Picker.PickerBase.RelativePosition" />
        /// </summary>
        /// <remarks>
        /// Accepts single View element.
        /// </remarks>
        [Parameter] public RenderFragment RelativeView { get; set; }
        /// <summary>
        /// Gets or sets the value of selection view. This property can be used to customize the selection in Picker.
        /// </summary>
        /// <remarks>
        /// Accepts single PickerSelectionView element.
        /// </remarks>
        [Parameter] public RenderFragment SelectionView { get; set; }
        /// <summary>
        /// Gets or sets the picker item text style in Picker.
        /// </summary>
        /// <remarks>
        /// Accepts single PickerTextStyle element.
        /// </remarks>
        [Parameter] public RenderFragment TextStyle { get; set; }
        /// <summary>
        /// Occurs after the ok button clicked on SfPicker. This event is not applicable for while the footer view is not visible and the ok button is not visible.
        /// </summary>
        [Parameter] public EventCallback OnOkButtonClicked { get; set; }
        /// <summary>
        /// Occurs after the cancel button clicked on SfPicker. This event is not applicable for while the footer view is not visible.
        /// </summary>
        [Parameter] public EventCallback OnCancelButtonClicked { get; set; }
        /// <summary>
        /// Occurs after the picker popup is opened.
        /// </summary>
        [Parameter] public EventCallback OnOpened { get; set; }
        /// <summary>
        /// Occurs when the picker popup is closed.
        /// </summary>
        [Parameter] public EventCallback OnClosed { get; set; }
        /// <summary>
        /// Occurs when the picker popup is closing.
        /// </summary>
        [Parameter] public EventCallback<CancelEventArgs> OnClosing { get; set; }

        public new SMTP.PickerBase NativeControl => (SMTP.PickerBase)((BindableObject)this).NativeControl;


        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(ColumnDividerColor):
                    if (!Equals(ColumnDividerColor, value))
                    {
                        ColumnDividerColor = (Color)value;
                        NativeControl.ColumnDividerColor = ColumnDividerColor;
                    }
                    break;
                case nameof(EnableLooping):
                    if (!Equals(EnableLooping, value))
                    {
                        EnableLooping = (bool?)value;
                        NativeControl.EnableLooping = EnableLooping ?? (bool)SMTP.PickerBase.EnableLoopingProperty.DefaultValue;
                    }
                    break;
                case nameof(IsOpen):
                    if (!Equals(IsOpen, value))
                    {
                        IsOpen = (bool?)value;
                        NativeControl.IsOpen = IsOpen ?? (bool)SMTP.PickerBase.IsOpenProperty.DefaultValue;
                    }
                    break;
                case nameof(ItemHeight):
                    if (!Equals(ItemHeight, value))
                    {
                        ItemHeight = (double?)value;
                        NativeControl.ItemHeight = ItemHeight ?? (double)SMTP.PickerBase.ItemHeightProperty.DefaultValue;
                    }
                    break;
                case nameof(Mode):
                    if (!Equals(Mode, value))
                    {
                        Mode = (SMTP.PickerMode?)value;
                        NativeControl.Mode = Mode ?? (SMTP.PickerMode)SMTP.PickerBase.ModeProperty.DefaultValue;
                    }
                    break;
                case nameof(PopupHeight):
                    if (!Equals(PopupHeight, value))
                    {
                        PopupHeight = (double?)value;
                        NativeControl.PopupHeight = PopupHeight ?? (double)SMTP.PickerBase.PopupHeightProperty.DefaultValue;
                    }
                    break;
                case nameof(PopupWidth):
                    if (!Equals(PopupWidth, value))
                    {
                        PopupWidth = (double?)value;
                        NativeControl.PopupWidth = PopupWidth ?? (double)SMTP.PickerBase.PopupWidthProperty.DefaultValue;
                    }
                    break;
                case nameof(RelativePosition):
                    if (!Equals(RelativePosition, value))
                    {
                        RelativePosition = (SMTP.PickerRelativePosition?)value;
                        NativeControl.RelativePosition = RelativePosition ?? (SMTP.PickerRelativePosition)SMTP.PickerBase.RelativePositionProperty.DefaultValue;
                    }
                    break;
                case nameof(SelectedTextStyle):
                    if (!Equals(SelectedTextStyle, value))
                    {
                        SelectedTextStyle = (SMTP.PickerTextStyle)value;
                        NativeControl.SelectedTextStyle = SelectedTextStyle;
                    }
                    break;
                case nameof(TextDisplayMode):
                    if (!Equals(TextDisplayMode, value))
                    {
                        TextDisplayMode = (SMTP.PickerTextDisplayMode?)value;
                        NativeControl.TextDisplayMode = TextDisplayMode ?? (SMTP.PickerTextDisplayMode)SMTP.PickerBase.TextDisplayModeProperty.DefaultValue;
                    }
                    break;
                case nameof(ColumnHeaderTemplate):
                    ColumnHeaderTemplate = (RenderFragment)value;
                    break;
                case nameof(FooterTemplate):
                    FooterTemplate = (RenderFragment)value;
                    break;
                case nameof(FooterView):
                    FooterView = (RenderFragment)value;
                    break;
                case nameof(HeaderTemplate):
                    HeaderTemplate = (RenderFragment)value;
                    break;
                case nameof(RelativeView):
                    RelativeView = (RenderFragment)value;
                    break;
                case nameof(SelectionView):
                    SelectionView = (RenderFragment)value;
                    break;
                case nameof(TextStyle):
                    TextStyle = (RenderFragment)value;
                    break;
                case nameof(OnOkButtonClicked):
                    if (!Equals(OnOkButtonClicked, value))
                    {
                        void NativeControlOkButtonClicked(object sender, EventArgs e) => InvokeEventCallback(OnOkButtonClicked);

                        OnOkButtonClicked = (EventCallback)value;
                        NativeControl.OkButtonClicked -= NativeControlOkButtonClicked;
                        NativeControl.OkButtonClicked += NativeControlOkButtonClicked;
                    }
                    break;
                case nameof(OnCancelButtonClicked):
                    if (!Equals(OnCancelButtonClicked, value))
                    {
                        void NativeControlCancelButtonClicked(object sender, EventArgs e) => InvokeEventCallback(OnCancelButtonClicked);

                        OnCancelButtonClicked = (EventCallback)value;
                        NativeControl.CancelButtonClicked -= NativeControlCancelButtonClicked;
                        NativeControl.CancelButtonClicked += NativeControlCancelButtonClicked;
                    }
                    break;
                case nameof(OnOpened):
                    if (!Equals(OnOpened, value))
                    {
                        void NativeControlOpened(object sender, EventArgs e) => InvokeEventCallback(OnOpened);

                        OnOpened = (EventCallback)value;
                        NativeControl.Opened -= NativeControlOpened;
                        NativeControl.Opened += NativeControlOpened;
                    }
                    break;
                case nameof(OnClosed):
                    if (!Equals(OnClosed, value))
                    {
                        void NativeControlClosed(object sender, EventArgs e) => InvokeEventCallback(OnClosed);

                        OnClosed = (EventCallback)value;
                        NativeControl.Closed -= NativeControlClosed;
                        NativeControl.Closed += NativeControlClosed;
                    }
                    break;
                case nameof(OnClosing):
                    if (!Equals(OnClosing, value))
                    {
                        void NativeControlClosing(object sender, CancelEventArgs e) => InvokeEventCallback(OnClosing, e);

                        OnClosing = (EventCallback<CancelEventArgs>)value;
                        NativeControl.Closing -= NativeControlClosing;
                        NativeControl.Closing += NativeControlClosing;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddDataTemplateProperty<SMTP.PickerBase>(builder, sequence++, ColumnHeaderTemplate, (x, template) => x.ColumnHeaderTemplate = template);
            RenderTreeBuilderHelper.AddDataTemplateProperty<SMTP.PickerBase>(builder, sequence++, FooterTemplate, (x, template) => x.FooterTemplate = template);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PickerBase>(builder, sequence++, FooterView, (x, value) => x.FooterView = (SMTP.PickerFooterView)value);
            RenderTreeBuilderHelper.AddDataTemplateProperty<SMTP.PickerBase>(builder, sequence++, HeaderTemplate, (x, template) => x.HeaderTemplate = template);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PickerBase>(builder, sequence++, RelativeView, (x, value) => x.RelativeView = (MC.View)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PickerBase>(builder, sequence++, SelectionView, (x, value) => x.SelectionView = (SMTP.PickerSelectionView)value);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.PickerBase>(builder, sequence++, TextStyle, (x, value) => x.TextStyle = (SMTP.PickerTextStyle)value);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
