// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using MCS = Microsoft.Maui.Controls.Shapes;
using Microsoft.AspNetCore.Components;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Shapes
{
    public partial class Transform : BlazorBindings.Maui.Elements.BindableObject
    {
        static Transform()
        {
            RegisterAdditionalHandlers();
        }

        [Parameter] public MCS.Matrix? Value { get; set; }

        public new MCS.Transform NativeControl => (MCS.Transform)((BindableObject)this).NativeControl;

        protected override MCS.Transform CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(Value):
                    if (!Equals(Value, value))
                    {
                        Value = (MCS.Matrix?)value;
                        NativeControl.Value = Value ?? (MCS.Matrix)MCS.Transform.ValueProperty.DefaultValue;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
