// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Rendering;
using SMTP = Syncfusion.Maui.Toolkit.ProgressBar;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Syncfusion.Toolkit.ProgressBar
{
    /// <summary>
    /// Represents <see cref="T:Syncfusion.Maui.Toolkit.ProgressBar.SfCircularProgressBar" /> class, which is a UI control that displays a circular progress indicator. This control allows for visualizing the progress of an operation through a customizable bar It supports features such as determinate and indeterminate progress modes, secondary progress indication, customizable appearance including track and progress colors, segment divisions, corner radius customization, and animation effects.
    /// </summary>
    public partial class SfCircularProgressBar : ProgressBarBase
    {
        static SfCircularProgressBar()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets a value that specifies the <see cref="P:Syncfusion.Maui.Toolkit.ProgressBar.SfCircularProgressBar.EndAngle" /> of the progress bar.
        /// </summary>
        /// <value>
        /// It defines the end angle of the progress bar. The default value is <c>630</c>.
        /// </value>
        [Parameter] public double? EndAngle { get; set; }
        /// <summary>
        /// Gets or sets the value that specifies the corner style of the progress.
        /// </summary>
        /// <value>
        /// One of the enumeration values that specifies the corner style of the progress in progress bar. The default is <see cref="F:Syncfusion.Maui.Toolkit.ProgressBar.CornerStyle.BothFlat" />.
        /// </value>
        [Parameter] public SMTP.CornerStyle? ProgressCornerStyle { get; set; }
        /// <summary>
        /// Gets or sets a value that specifies the outer radius factor of the progress.
        /// </summary>
        /// <value>
        /// It defines the radius factor of the progress. The default value is <c>0.9</c>.
        /// </value>
        [Parameter] public double? ProgressRadiusFactor { get; set; }
        /// <summary>
        /// Gets or sets a value that specifies the thickness for the progress. You can specify value either in logical pixel or radius factor using the <see cref="P:Syncfusion.Maui.Toolkit.ProgressBar.SfCircularProgressBar.ThicknessUnit" /> property.
        /// </summary>
        /// <value>
        /// The default value is <c>5</c>.
        /// </value>
        [Parameter] public double? ProgressThickness { get; set; }
        /// <summary>
        /// Gets or sets a value that specifies the <see cref="P:Syncfusion.Maui.Toolkit.ProgressBar.SfCircularProgressBar.StartAngle" /> of the progress bar.
        /// </summary>
        /// <value>
        /// It defines the start angle of the progress bar. The default value is <c>270</c>.
        /// </value>
        [Parameter] public double? StartAngle { get; set; }
        /// <summary>
        /// Gets or sets enum value that indicates to calculate the track and progress thickness either in logical pixel or radius factor.
        /// </summary>
        /// <value>
        /// One of the <see cref="T:Syncfusion.Maui.Toolkit.ProgressBar.SizeUnit" /> enumeration that specifies how the thickness unit value is considered. The default mode is <see cref="F:Syncfusion.Maui.Toolkit.ProgressBar.SizeUnit.Pixel" />.
        /// </value>
        [Parameter] public SMTP.SizeUnit? ThicknessUnit { get; set; }
        /// <summary>
        /// Gets or sets the value that specifies the corner style of the track.
        /// </summary>
        /// <value>
        /// One of the enumeration values that specifies the corner style of the track in progress bar. The default is <see cref="F:Syncfusion.Maui.Toolkit.ProgressBar.CornerStyle.BothFlat" />.
        /// </value>
        [Parameter] public SMTP.CornerStyle? TrackCornerStyle { get; set; }
        /// <summary>
        /// Gets or sets a value that specifies the outer radius factor of the track.
        /// </summary>
        /// <value>
        /// This value ranges from 0 to 1. It defines the radius factor of the track. The default value is <c>0.9</c>.
        /// </value>
        [Parameter] public double? TrackRadiusFactor { get; set; }
        /// <summary>
        /// Gets or sets a value that specifies the thickness of track in circular progress bar. You can specify value either in logical pixel or radius factor using the <see cref="P:Syncfusion.Maui.Toolkit.ProgressBar.SfCircularProgressBar.ThicknessUnit" /> property.
        /// </summary>
        /// <value>
        /// The default value is <c>5</c>.
        /// </value>
        [Parameter] public double? TrackThickness { get; set; }
        /// <summary>
        /// Gets or sets a any view to display in the center of circular progress bar.
        /// </summary>
        /// <value>
        /// An object that contains the progress bar visual content. The default value is <c>null</c>.
        /// </value>
        /// <remarks>
        /// Accepts single View element.
        /// </remarks>
        [Parameter] public new RenderFragment ChildContent { get; set; }

        public new SMTP.SfCircularProgressBar NativeControl => (SMTP.SfCircularProgressBar)((BindableObject)this).NativeControl;

        protected override SMTP.SfCircularProgressBar CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(EndAngle):
                    if (!Equals(EndAngle, value))
                    {
                        EndAngle = (double?)value;
                        NativeControl.EndAngle = EndAngle ?? (double)SMTP.SfCircularProgressBar.EndAngleProperty.DefaultValue;
                    }
                    break;
                case nameof(ProgressCornerStyle):
                    if (!Equals(ProgressCornerStyle, value))
                    {
                        ProgressCornerStyle = (SMTP.CornerStyle?)value;
                        NativeControl.ProgressCornerStyle = ProgressCornerStyle ?? (SMTP.CornerStyle)SMTP.SfCircularProgressBar.ProgressCornerStyleProperty.DefaultValue;
                    }
                    break;
                case nameof(ProgressRadiusFactor):
                    if (!Equals(ProgressRadiusFactor, value))
                    {
                        ProgressRadiusFactor = (double?)value;
                        NativeControl.ProgressRadiusFactor = ProgressRadiusFactor ?? (double)SMTP.SfCircularProgressBar.ProgressRadiusFactorProperty.DefaultValue;
                    }
                    break;
                case nameof(ProgressThickness):
                    if (!Equals(ProgressThickness, value))
                    {
                        ProgressThickness = (double?)value;
                        NativeControl.ProgressThickness = ProgressThickness ?? (double)SMTP.SfCircularProgressBar.ProgressThicknessProperty.DefaultValue;
                    }
                    break;
                case nameof(StartAngle):
                    if (!Equals(StartAngle, value))
                    {
                        StartAngle = (double?)value;
                        NativeControl.StartAngle = StartAngle ?? (double)SMTP.SfCircularProgressBar.StartAngleProperty.DefaultValue;
                    }
                    break;
                case nameof(ThicknessUnit):
                    if (!Equals(ThicknessUnit, value))
                    {
                        ThicknessUnit = (SMTP.SizeUnit?)value;
                        NativeControl.ThicknessUnit = ThicknessUnit ?? (SMTP.SizeUnit)SMTP.SfCircularProgressBar.ThicknessUnitProperty.DefaultValue;
                    }
                    break;
                case nameof(TrackCornerStyle):
                    if (!Equals(TrackCornerStyle, value))
                    {
                        TrackCornerStyle = (SMTP.CornerStyle?)value;
                        NativeControl.TrackCornerStyle = TrackCornerStyle ?? (SMTP.CornerStyle)SMTP.SfCircularProgressBar.TrackCornerStyleProperty.DefaultValue;
                    }
                    break;
                case nameof(TrackRadiusFactor):
                    if (!Equals(TrackRadiusFactor, value))
                    {
                        TrackRadiusFactor = (double?)value;
                        NativeControl.TrackRadiusFactor = TrackRadiusFactor ?? (double)SMTP.SfCircularProgressBar.TrackRadiusFactorProperty.DefaultValue;
                    }
                    break;
                case nameof(TrackThickness):
                    if (!Equals(TrackThickness, value))
                    {
                        TrackThickness = (double?)value;
                        NativeControl.TrackThickness = TrackThickness ?? (double)SMTP.SfCircularProgressBar.TrackThicknessProperty.DefaultValue;
                    }
                    break;
                case nameof(ChildContent):
                    ChildContent = (RenderFragment)value;
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        protected override void RenderAdditionalElementContent(RenderTreeBuilder builder, ref int sequence)
        {
            base.RenderAdditionalElementContent(builder, ref sequence);
            RenderTreeBuilderHelper.AddContentProperty<SMTP.SfCircularProgressBar>(builder, sequence++, ChildContent, (x, value) => x.Content = (MC.View)value);
        }

        static partial void RegisterAdditionalHandlers();
    }
}
