// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using MCM = Material.Components.Maui;
using Microsoft.AspNetCore.Components;
using Microsoft.Maui.Graphics;
using System;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Material.Components
{
    public partial class MDNavigationDrawerItem : SKTouchCanvasView
    {
        static MDNavigationDrawerItem()
        {
            RegisterAdditionalHandlers();
        }

        [Parameter] public Color ActiveIndicatorColor { get; set; }
        [Parameter] public Color BackgroundColour { get; set; }
        [Parameter] public Type ContentType { get; set; }
        [Parameter] public string FontFamily { get; set; }
        [Parameter] public bool? FontItalic { get; set; }
        [Parameter] public float? FontSize { get; set; }
        [Parameter] public int? FontWeight { get; set; }
        [Parameter] public Color ForegroundColor { get; set; }
        [Parameter] public string IconData { get; set; }
        [Parameter] public global::IconPacks.Material.IconKind? IconKind { get; set; }
        [Parameter] public global::SkiaSharp.SKPicture IconSource { get; set; }
        [Parameter] public bool? IsActived { get; set; }
        [Parameter] public bool? IsExtended { get; set; }
        [Parameter] public Color RippleColor { get; set; }
        [Parameter] public Color StateLayerColor { get; set; }
        [Parameter] public string Text { get; set; }
        [Parameter] public string Title { get; set; }

        public new MCM.NavigationDrawerItem NativeControl => (MCM.NavigationDrawerItem)((BindableObject)this).NativeControl;

        protected override MCM.NavigationDrawerItem CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(ActiveIndicatorColor):
                    if (!Equals(ActiveIndicatorColor, value))
                    {
                        ActiveIndicatorColor = CastParameter<Color>(value, name);
                        NativeControl.ActiveIndicatorColor = ActiveIndicatorColor;
                    }
                    break;
                case nameof(BackgroundColour):
                    if (!Equals(BackgroundColour, value))
                    {
                        BackgroundColour = CastParameter<Color>(value, name);
                        NativeControl.BackgroundColour = BackgroundColour;
                    }
                    break;
                case nameof(ContentType):
                    if (!Equals(ContentType, value))
                    {
                        ContentType = CastParameter<Type>(value, name);
                        NativeControl.ContentType = ContentType;
                    }
                    break;
                case nameof(FontFamily):
                    if (!Equals(FontFamily, value))
                    {
                        FontFamily = CastParameter<string>(value, name);
                        NativeControl.FontFamily = FontFamily;
                    }
                    break;
                case nameof(FontItalic):
                    if (!Equals(FontItalic, value))
                    {
                        FontItalic = CastParameter<bool?>(value, name);
                        NativeControl.FontItalic = FontItalic ?? (bool)MCM.NavigationDrawerItem.FontItalicProperty.DefaultValue;
                    }
                    break;
                case nameof(FontSize):
                    if (!Equals(FontSize, value))
                    {
                        FontSize = CastParameter<float?>(value, name);
                        NativeControl.FontSize = FontSize ?? (float)MCM.NavigationDrawerItem.FontSizeProperty.DefaultValue;
                    }
                    break;
                case nameof(FontWeight):
                    if (!Equals(FontWeight, value))
                    {
                        FontWeight = CastParameter<int?>(value, name);
                        NativeControl.FontWeight = FontWeight ?? (int)MCM.NavigationDrawerItem.FontWeightProperty.DefaultValue;
                    }
                    break;
                case nameof(ForegroundColor):
                    if (!Equals(ForegroundColor, value))
                    {
                        ForegroundColor = CastParameter<Color>(value, name);
                        NativeControl.ForegroundColor = ForegroundColor;
                    }
                    break;
                case nameof(IconData):
                    if (!Equals(IconData, value))
                    {
                        IconData = CastParameter<string>(value, name);
                        NativeControl.IconData = IconData;
                    }
                    break;
                case nameof(IconKind):
                    if (!Equals(IconKind, value))
                    {
                        IconKind = CastParameter<global::IconPacks.Material.IconKind?>(value, name);
                        NativeControl.IconKind = IconKind ?? (global::IconPacks.Material.IconKind)MCM.NavigationDrawerItem.IconKindProperty.DefaultValue;
                    }
                    break;
                case nameof(IconSource):
                    if (!Equals(IconSource, value))
                    {
                        IconSource = CastParameter<global::SkiaSharp.SKPicture>(value, name);
                        NativeControl.IconSource = IconSource;
                    }
                    break;
                case nameof(IsActived):
                    if (!Equals(IsActived, value))
                    {
                        IsActived = CastParameter<bool?>(value, name);
                        NativeControl.IsActived = IsActived ?? (bool)MCM.NavigationDrawerItem.IsActivedProperty.DefaultValue;
                    }
                    break;
                case nameof(IsExtended):
                    if (!Equals(IsExtended, value))
                    {
                        IsExtended = CastParameter<bool?>(value, name);
                        NativeControl.IsExtended = IsExtended ?? (bool)MCM.NavigationDrawerItem.IsExtendedProperty.DefaultValue;
                    }
                    break;
                case nameof(RippleColor):
                    if (!Equals(RippleColor, value))
                    {
                        RippleColor = CastParameter<Color>(value, name);
                        NativeControl.RippleColor = RippleColor;
                    }
                    break;
                case nameof(StateLayerColor):
                    if (!Equals(StateLayerColor, value))
                    {
                        StateLayerColor = CastParameter<Color>(value, name);
                        NativeControl.StateLayerColor = StateLayerColor;
                    }
                    break;
                case nameof(Text):
                    if (!Equals(Text, value))
                    {
                        Text = CastParameter<string>(value, name);
                        NativeControl.Text = Text;
                    }
                    break;
                case nameof(Title):
                    if (!Equals(Title, value))
                    {
                        Title = CastParameter<string>(value, name);
                        NativeControl.Title = Title;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
