// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using MCM = Material.Components.Maui;
using Microsoft.AspNetCore.Components;
using Microsoft.Maui.Graphics;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.Material.Components
{
    public partial class MDSwitch : SKTouchCanvasView
    {
        static MDSwitch()
        {
            RegisterAdditionalHandlers();
        }

        [Parameter] public MCM.ControlState? ControlState { get; set; }
        [Parameter] public bool? HasIcon { get; set; }
        [Parameter] public Color IconColor { get; set; }
        [Parameter] public float? IconOpacity { get; set; }
        [Parameter] public bool? IsChecked { get; set; }
        [Parameter] public Color OutlineColor { get; set; }
        [Parameter] public int? OutlineWidth { get; set; }
        [Parameter] public Color RippleColor { get; set; }
        [Parameter] public MCM.Tokens.Shape? Shape { get; set; }
        [Parameter] public Color StateLayerColor { get; set; }
        [Parameter] public Color ThumbColor { get; set; }
        [Parameter] public float? ThumbOpacity { get; set; }
        [Parameter] public Color TrackColor { get; set; }
        [Parameter] public float? TrackOpacity { get; set; }
        [Parameter] public EventCallback<bool> IsCheckedChanged { get; set; }

        public new MCM.Switch NativeControl => (MCM.Switch)((BindableObject)this).NativeControl;

        protected override MCM.Switch CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(ControlState):
                    if (!Equals(ControlState, value))
                    {
                        ControlState = CastParameter<MCM.ControlState?>(value, name);
                        NativeControl.ControlState = ControlState ?? default;
                    }
                    break;
                case nameof(HasIcon):
                    if (!Equals(HasIcon, value))
                    {
                        HasIcon = CastParameter<bool?>(value, name);
                        NativeControl.HasIcon = HasIcon ?? (bool)MCM.Switch.HasIconProperty.DefaultValue;
                    }
                    break;
                case nameof(IconColor):
                    if (!Equals(IconColor, value))
                    {
                        IconColor = CastParameter<Color>(value, name);
                        NativeControl.IconColor = IconColor;
                    }
                    break;
                case nameof(IconOpacity):
                    if (!Equals(IconOpacity, value))
                    {
                        IconOpacity = CastParameter<float?>(value, name);
                        NativeControl.IconOpacity = IconOpacity ?? (float)MCM.Switch.IconOpacityProperty.DefaultValue;
                    }
                    break;
                case nameof(IsChecked):
                    if (!Equals(IsChecked, value))
                    {
                        IsChecked = CastParameter<bool?>(value, name);
                        NativeControl.IsChecked = IsChecked ?? (bool)MCM.Switch.IsCheckedProperty.DefaultValue;
                    }
                    break;
                case nameof(OutlineColor):
                    if (!Equals(OutlineColor, value))
                    {
                        OutlineColor = CastParameter<Color>(value, name);
                        NativeControl.OutlineColor = OutlineColor;
                    }
                    break;
                case nameof(OutlineWidth):
                    if (!Equals(OutlineWidth, value))
                    {
                        OutlineWidth = CastParameter<int?>(value, name);
                        NativeControl.OutlineWidth = OutlineWidth ?? (int)MCM.Switch.OutlineWidthProperty.DefaultValue;
                    }
                    break;
                case nameof(RippleColor):
                    if (!Equals(RippleColor, value))
                    {
                        RippleColor = CastParameter<Color>(value, name);
                        NativeControl.RippleColor = RippleColor;
                    }
                    break;
                case nameof(Shape):
                    if (!Equals(Shape, value))
                    {
                        Shape = CastParameter<MCM.Tokens.Shape?>(value, name);
                        NativeControl.Shape = Shape ?? (MCM.Tokens.Shape)MCM.Switch.ShapeProperty.DefaultValue;
                    }
                    break;
                case nameof(StateLayerColor):
                    if (!Equals(StateLayerColor, value))
                    {
                        StateLayerColor = CastParameter<Color>(value, name);
                        NativeControl.StateLayerColor = StateLayerColor;
                    }
                    break;
                case nameof(ThumbColor):
                    if (!Equals(ThumbColor, value))
                    {
                        ThumbColor = CastParameter<Color>(value, name);
                        NativeControl.ThumbColor = ThumbColor;
                    }
                    break;
                case nameof(ThumbOpacity):
                    if (!Equals(ThumbOpacity, value))
                    {
                        ThumbOpacity = CastParameter<float?>(value, name);
                        NativeControl.ThumbOpacity = ThumbOpacity ?? (float)MCM.Switch.ThumbOpacityProperty.DefaultValue;
                    }
                    break;
                case nameof(TrackColor):
                    if (!Equals(TrackColor, value))
                    {
                        TrackColor = CastParameter<Color>(value, name);
                        NativeControl.TrackColor = TrackColor;
                    }
                    break;
                case nameof(TrackOpacity):
                    if (!Equals(TrackOpacity, value))
                    {
                        TrackOpacity = CastParameter<float?>(value, name);
                        NativeControl.TrackOpacity = TrackOpacity ?? (float)MCM.Switch.TrackOpacityProperty.DefaultValue;
                    }
                    break;
                case nameof(IsCheckedChanged):
                    if (!Equals(IsCheckedChanged, value))
                    {
                        void NativeControlCheckedChanged(object sender, MC.CheckedChangedEventArgs e)
                        {
                            var value = NativeControl.IsChecked;
                            IsChecked = value;
                            InvokeEventCallback(IsCheckedChanged, value);
                        }

                        IsCheckedChanged = CastParameter<EventCallback<bool>>(value, name);
                        NativeControl.CheckedChanged -= NativeControlCheckedChanged;
                        NativeControl.CheckedChanged += NativeControlCheckedChanged;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
