using System.Diagnostics;

#pragma warning disable CS9113 // Parameter is unread. Type is used by Component Generator.

namespace BlazorBindings.Maui.ComponentGenerator;

/// <summary>
/// Instructs the BlazorBindings.Maui component generator to create a Blazor wrapper component
/// for the specified MAUI type. Place this attribute at the assembly level, typically in a
/// dedicated <c>Elements.cs</c> file inside a <c>Properties</c> folder.
/// </summary>
/// <param name="typeToGenerate">
/// The MAUI type for which a Blazor component will be generated.
/// Open generic types (e.g. <c>typeof(Popup&lt;&gt;)</c>) are supported.
/// </param>
/// <example>
/// Basic usage — generate a component with no customization:
/// <code>
/// [assembly: GenerateComponent(typeof(MyControl))]
/// </code>
/// </example>
[Conditional("CODE_ANALYSIS")]
[AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
public class GenerateComponentAttribute(Type typeToGenerate) : Attribute
{
    /// <summary>
    /// Names of MAUI type members (properties or events) that should be omitted from the
    /// generated component. Use this to suppress members that are unsupported, unsafe, or
    /// already covered by a base component.
    /// </summary>
    /// <remarks>
    /// Members that have unsupported types (e.g. <c>ICommand</c>, <c>Font</c>) are already
    /// excluded automatically; <see cref="Exclude"/> is only needed for members that would
    /// otherwise be included.
    /// </remarks>
    /// <example>
    /// <code>
    /// [assembly: GenerateComponent(typeof(AvatarView),
    ///     Exclude = [nameof(AvatarView.CornerRadius)])]
    /// </code>
    /// </example>
    public string[] Exclude { get; set; }

    /// <summary>
    /// Names of MAUI type members that should be included in the generated component even
    /// though the generator would normally exclude them. This is useful for properties with
    /// types that are not auto-detected as suitable (e.g. <c>object</c>-typed properties,
    /// or properties on a generic base type).
    /// </summary>
    /// <remarks>
    /// Members from a generic base class are not enumerated automatically; list them here to
    /// pull them into the generated component.
    /// </remarks>
    /// <example>
    /// <code>
    /// [assembly: GenerateComponent(typeof(SelectableItemsView),
    ///     Include = [nameof(SelectableItemsView.SelectedItem)])]
    /// </code>
    /// </example>
    public string[] Include { get; set; }

    /// <summary>
    /// Names of MAUI properties for which an <c>EventCallback</c> parameter should be
    /// generated by listening to the <c>PropertyChanged</c> event and filtering by property
    /// name, rather than to a dedicated <c>&lt;PropertyName&gt;Changed</c> event.
    /// The generated parameter is named <c>&lt;PropertyName&gt;Changed</c>.
    /// </summary>
    /// <remarks>
    /// Use this when the MAUI control does not expose a dedicated changed event for a
    /// two-way-bindable property but does fire <c>INotifyPropertyChanged.PropertyChanged</c>.
    /// </remarks>
    /// <example>
    /// <code>
    /// [assembly: GenerateComponent(typeof(MySlider),
    ///     PropertyChangedEvents = [nameof(MySlider.Value)])]
    /// // Generates: [Parameter] public EventCallback&lt;double&gt; ValueChanged { get; set; }
    /// </code>
    /// </example>
    public string[] PropertyChangedEvents { get; set; }

    /// <summary>
    /// Specifies properties that should be generated as generic Blazor parameters, making the
    /// entire component generic (e.g. <c>MyComponent&lt;T&gt;</c>). Each entry is either:
    /// <list type="bullet">
    ///   <item><description>
    ///     <c>"PropertyName"</c> — the property becomes <c>T</c>-typed (unconstrained).
    ///   </description></item>
    ///   <item><description>
    ///     <c>"PropertyName:Fully.Qualified.ConstraintType"</c> — the property becomes
    ///     <c>T</c>-typed with <c>where T : ConstraintType</c>.
    ///   </description></item>
    /// </list>
    /// </summary>
    /// <remarks>
    /// Properties whose MAUI type is <c>object</c> or <c>IList</c> require this setting to
    /// produce a usefully typed generic parameter; otherwise they remain <c>object</c>-typed.
    /// Setting any entry here automatically sets <see cref="IsGeneric"/> to <c>true</c>.
    /// </remarks>
    /// <example>
    /// Constrained generic — the generated component accepts only <c>ICalendarDay</c> subtypes:
    /// <code>
    /// [assembly: GenerateComponent(typeof(CalendarView),
    ///     GenericProperties = [
    ///         $"{nameof(CalendarView.DayTemplate)}:XCalendar.Core.Interfaces.ICalendarDay",
    ///     ])]
    /// // Generates: CalendarView&lt;T&gt; where T : ICalendarDay
    /// //            [Parameter] public RenderFragment&lt;T&gt; DayTemplate { get; set; }
    /// </code>
    /// Unconstrained generic:
    /// <code>
    /// [assembly: GenerateComponent(typeof(MyPicker),
    ///     GenericProperties = [nameof(MyPicker.SelectedItem)])]
    /// // Generates: MyPicker&lt;T&gt;
    /// //            [Parameter] public T? SelectedItem { get; set; }
    /// </code>
    /// </example>
    public string[] GenericProperties { get; set; }

    /// <summary>
    /// Names of MAUI properties that should be generated as <c>RenderFragment</c> (child
    /// content) parameters even though the generator would not treat them as content
    /// automatically. Properties of MAUI element or list-of-element types are already
    /// detected automatically; use this only for edge cases.
    /// </summary>
    /// <remarks>
    /// A property listed here takes priority over the auto-detection logic in
    /// <c>IsRenderFragmentPropertySymbol</c>. The inverse is <see cref="NonContentProperties"/>.
    /// </remarks>
    /// <example>
    /// <code>
    /// [assembly: GenerateComponent(typeof(MyView),
    ///     ContentProperties = [nameof(MyView.Header)])]
    /// // Generates: [Parameter] public RenderFragment Header { get; set; }
    /// </code>
    /// </example>
    public string[] ContentProperties { get; set; }

    /// <summary>
    /// Names of MAUI properties that should be generated as a plain value parameter even
    /// though the generator would otherwise treat them as <c>RenderFragment</c> content.
    /// Useful when a property holds a reference to an existing element rather than defining
    /// new child content (e.g. <c>SelectedItem</c>, <c>CurrentPage</c>).
    /// </summary>
    /// <remarks>
    /// Properties whose names contain <c>Visible</c>, <c>Selected</c>, or <c>Current</c> are
    /// already excluded from RenderFragment generation automatically. Use
    /// <see cref="NonContentProperties"/> for other cases. The inverse is
    /// <see cref="ContentProperties"/>.
    /// </remarks>
    /// <example>
    /// <code>
    /// [assembly: GenerateComponent(typeof(CarouselView),
    ///     NonContentProperties = [nameof(CarouselView.CurrentItem)])]
    /// </code>
    /// </example>
    public string[] NonContentProperties { get; set; }

    /// <summary>
    /// Renames generated Blazor parameters so they differ from their MAUI counterparts.
    /// Each entry must follow the format <c>"MauiMemberName:GeneratedParameterName"</c>.
    /// Applies to both value properties and <c>RenderFragment</c> content properties
    /// (the alias is used as the Blazor-side name in both cases).
    /// </summary>
    /// <example>
    /// Rename an open generic type so the generated component has a friendlier name:
    /// <code>
    /// [assembly: GenerateComponent(typeof(Popup&lt;&gt;),
    ///     Aliases = ["Popup:PopupWithResult"])]
    /// // Generated class name: PopupWithResult&lt;T&gt;
    /// </code>
    /// Rename a property:
    /// <code>
    /// [assembly: GenerateComponent(typeof(MyControl),
    ///     Aliases = ["LegacyCaption:Title"])]
    /// // Generates: [Parameter] public string? Title { get; set; }
    /// //            (backed by NativeControl.LegacyCaption)
    /// </code>
    /// </example>
    public string[] Aliases { get; set; }

    /// <summary>
    /// Forces the generated component to be a generic class (<c>MyComponent&lt;T&gt;</c>)
    /// even when no specific <see cref="GenericProperties"/> are provided. The type parameter
    /// <c>T</c> is unconstrained.
    /// </summary>
    /// <remarks>
    /// This is implied automatically when <see cref="GenericProperties"/> contains any entry
    /// without a constraint type, or when <see cref="MakeItemsGeneric"/> resolves to
    /// <c>true</c>. Set this explicitly only when you need a generic shell component without
    /// any generic-typed properties.
    /// </remarks>
    /// <example>
    /// <code>
    /// [assembly: GenerateComponent(typeof(MyView), IsGeneric = true)]
    /// // Generates: public partial class MyView&lt;T&gt; : ...
    /// </code>
    /// </example>
    public bool IsGeneric { get; set; }

    /// <summary>
    /// Controls whether the well-known collection-related properties
    /// (<c>ItemsSource</c>, <c>SelectedItem</c>, <c>CurrentItem</c>, <c>ItemTemplate</c>,
    /// <c>ItemTemplateSelector</c>, <c>ItemDisplayBinding</c>) are automatically made generic
    /// (<c>T</c>-typed), turning the component into a generic class.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The generator enables this automatically when the MAUI type exposes a public-setter
    /// <c>ItemsSource</c> property <em>and</em> is not decorated with
    /// <c>[ContentProperty]</c>, because in that case <c>ItemsSource</c> is considered the
    /// primary input and a generic type argument is always required anyway.
    /// </para>
    /// <para>
    /// Set to <c>false</c> to opt out when the automatic heuristic is too aggressive — for
    /// example, when the component also has a <c>[ContentProperty]</c> child-items approach
    /// and making it generic would be inconvenient for callers who don't supply
    /// <c>ItemsSource</c>.
    /// </para>
    /// </remarks>
    /// <example>
    /// Opt out of automatic generic items:
    /// <code>
    /// [assembly: GenerateComponent(typeof(SfTabView), MakeItemsGeneric = false)]
    /// // Generates a non-generic SfTabView component even though it has ItemsSource.
    /// </code>
    /// </example>
    public bool MakeItemsGeneric { get; set; }

    /// <summary>
    /// Maps MAUI <c>ICommand</c> properties to Blazor <c>EventCallback</c> parameters.
    /// Each entry must follow the format <c>"CommandPropertyName:EventCallbackName"</c>.
    /// The generator will assign a <c>new Command(...)</c> to the native control's command
    /// property that invokes the Blazor callback when executed, and set it to <c>null</c>
    /// when the callback has no delegate.
    /// </summary>
    /// <remarks>
    /// The command property is automatically excluded from the generated value properties so
    /// it does not appear as a raw <c>ICommand</c> parameter alongside the callback.
    /// </remarks>
    /// <example>
    /// <code>
    /// [assembly: GenerateComponent(typeof(VirtualizeListView),
    ///     CommandEvents = ["ThresholdCommand:OnThreshold"])]
    /// // Generates: [Parameter] public EventCallback OnThreshold { get; set; }
    /// // Sets:      NativeControl.ThresholdCommand = new Command(() => InvokeEventCallback(OnThreshold));
    /// </code>
    /// </example>
    public string[] CommandEvents { get; set; }
}
