// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using CM = CommunityToolkit.Maui;
using CMB = CommunityToolkit.Maui.Behaviors;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using Microsoft.Maui.Graphics;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.CommunityToolkit.Behaviors
{
    public partial class StatusBarBehavior : BlazorBindings.Maui.Elements.Behavior
    {
        static StatusBarBehavior()
        {
            RegisterAdditionalHandlers();
        }

        [Parameter] public CMB.StatusBarApplyOn? ApplyOn { get; set; }
        [Parameter] public Color StatusBarColor { get; set; }
        [Parameter] public CM.Core.StatusBarStyle? StatusBarStyle { get; set; }

        public new CMB.StatusBarBehavior NativeControl => (CMB.StatusBarBehavior)((BindableObject)this).NativeControl;

        protected override CMB.StatusBarBehavior CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(ApplyOn):
                    if (!Equals(ApplyOn, value))
                    {
                        ApplyOn = (CMB.StatusBarApplyOn?)value;
                        NativeControl.ApplyOn = ApplyOn ?? (CMB.StatusBarApplyOn)CMB.StatusBarBehavior.ApplyOnProperty.DefaultValue;
                    }
                    break;
                case nameof(StatusBarColor):
                    if (!Equals(StatusBarColor, value))
                    {
                        StatusBarColor = (Color)value;
                        NativeControl.StatusBarColor = StatusBarColor;
                    }
                    break;
                case nameof(StatusBarStyle):
                    if (!Equals(StatusBarStyle, value))
                    {
                        StatusBarStyle = (CM.Core.StatusBarStyle?)value;
                        NativeControl.StatusBarStyle = StatusBarStyle ?? (CM.Core.StatusBarStyle)CMB.StatusBarBehavior.StatusBarStyleProperty.DefaultValue;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
