// <auto-generated>
//     This code was generated by a BlazorBindings.Maui component generator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

using BlazorBindings.Core;
using BlazorBindings.Maui.Elements;
using MC = Microsoft.Maui.Controls;
using Microsoft.AspNetCore.Components;
using SVMC = SkiaSharp.Views.Maui.Controls;
using System.Threading.Tasks;

#pragma warning disable MBB001

namespace BlazorBindings.Maui.Elements.SkiaSharp
{
    /// <summary>
    /// A .NET MAUI view that can be used to draw 2D graphics using SkiaSharp with software (CPU) rendering.
    /// </summary>
    public partial class SKCanvasView : BlazorBindings.Maui.Elements.View
    {
        static SKCanvasView()
        {
            RegisterAdditionalHandlers();
        }

        /// <summary>
        /// Gets or sets a value indicating whether touch events are enabled for this view.
        /// </summary>
        /// <value>
        /// <see langword="true" /> if touch events are enabled; otherwise, <see langword="false" />. The default is <see langword="false" />.
        /// </value>
        [Parameter] public bool? EnableTouchEvents { get; set; }
        /// <summary>
        /// Gets or sets a value indicating whether the canvas should ignore the device's pixel density scaling.
        /// </summary>
        /// <value>
        /// <see langword="true" /> to ignore pixel scaling and use 1:1 pixel mapping; otherwise, <see langword="false" />. The default is <see langword="false" />.
        /// </value>
        [Parameter] public bool? IgnorePixelScaling { get; set; }
        /// <summary>
        /// Occurs when the surface needs to be painted.
        /// </summary>
        [Parameter] public EventCallback<global::SkiaSharp.Views.Maui.SKPaintSurfaceEventArgs> OnPaintSurface { get; set; }
        /// <summary>
        /// Occurs when a touch event is detected on the view.
        /// </summary>
        [Parameter] public EventCallback<global::SkiaSharp.Views.Maui.SKTouchEventArgs> OnTouch { get; set; }

        public new SVMC.SKCanvasView NativeControl => (SVMC.SKCanvasView)((BindableObject)this).NativeControl;

        protected override SVMC.SKCanvasView CreateNativeElement() => new();

        protected override void HandleParameter(string name, object value)
        {
            switch (name)
            {
                case nameof(EnableTouchEvents):
                    if (!Equals(EnableTouchEvents, value))
                    {
                        EnableTouchEvents = CastParameter<bool?>(value, name);
                        NativeControl.EnableTouchEvents = EnableTouchEvents ?? (bool)SVMC.SKCanvasView.EnableTouchEventsProperty.DefaultValue;
                    }
                    break;
                case nameof(IgnorePixelScaling):
                    if (!Equals(IgnorePixelScaling, value))
                    {
                        IgnorePixelScaling = CastParameter<bool?>(value, name);
                        NativeControl.IgnorePixelScaling = IgnorePixelScaling ?? (bool)SVMC.SKCanvasView.IgnorePixelScalingProperty.DefaultValue;
                    }
                    break;
                case nameof(OnPaintSurface):
                    if (!Equals(OnPaintSurface, value))
                    {
                        void NativeControlPaintSurface(object sender, global::SkiaSharp.Views.Maui.SKPaintSurfaceEventArgs e) => InvokeEventCallback(OnPaintSurface, e);

                        OnPaintSurface = CastParameter<EventCallback<global::SkiaSharp.Views.Maui.SKPaintSurfaceEventArgs>>(value, name);
                        NativeControl.PaintSurface -= NativeControlPaintSurface;
                        NativeControl.PaintSurface += NativeControlPaintSurface;
                    }
                    break;
                case nameof(OnTouch):
                    if (!Equals(OnTouch, value))
                    {
                        void NativeControlTouch(object sender, global::SkiaSharp.Views.Maui.SKTouchEventArgs e) => InvokeEventCallback(OnTouch, e);

                        OnTouch = CastParameter<EventCallback<global::SkiaSharp.Views.Maui.SKTouchEventArgs>>(value, name);
                        NativeControl.Touch -= NativeControlTouch;
                        NativeControl.Touch += NativeControlTouch;
                    }
                    break;

                default:
                    base.HandleParameter(name, value);
                    break;
            }
        }

        static partial void RegisterAdditionalHandlers();
    }
}
