name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0        
    - name: Install .NET 6.0.300-preview.22204.3
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.300-preview.22204.3'
        include-prerelease: true
    - name: Install MAUI
      run: |
        dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore MobileBlazorBindings.sln
    - name: Build
      run: dotnet build --no-restore MobileBlazorBindings.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal
