name: .NET

on:
  push:
    branches: [ main, 'v[0-9].**' ]
  pull_request:
    branches: [ main, 'v[0-9].**' ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0        
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    - name: Install MAUI
      run: dotnet workload install maui
    - name: Restore dependencies
      run: dotnet restore BlazorBindings.Maui.sln
    - name: Run tests
      run: dotnet test src/BlazorBindings.UnitTests --no-restore --verbosity normal --collect:"XPlat Code Coverage"
    - name: Build templates
      run: |
        cd templates
        dotnet build -c Release --no-restore
        cd ..
    - name: Pack nugets
      run: dotnet pack -o ./packages -c Release --no-restore
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: packages

  publish-to-myget:
    runs-on: windows-2022
    needs: [build]
    steps:
    - uses: actions/download-artifact@v4
    
    - name: Publish to Myget
      run: dotnet nuget push */*.nupkg -k ${{ secrets.MYGET_TOKEN }} -s https://www.myget.org/F/blazorbindings/api/v2/package
